import MarkdownIt from "markdown-it";
import DOMPurify from "dompurify";
import type {JSX} from "react";
import {MermaidBlock} from "./MermaidBlock";
import type {DocumentAst,DocumentNode,ReportMode,ReportOrientation,ReportThemeName} from "./types";
const markdown=new MarkdownIt({html:false,linkify:true,typographer:true,breaks:true});
const inline=(value="")=>({__html:DOMPurify.sanitize(markdown.renderInline(value),{USE_PROFILES:{html:true}})});
const status=(value:string)=>/风险|停止|回退|下降|未达标/.test(value)?"risk":/观察|等待|保持|样本/.test(value)?"watch":/达标|通过|增长|继续|增加/.test(value)?"success":"info";
function BusinessBlock({node}:{node:DocumentNode}){const pairs=Object.entries(node.metadata||{});return <section className={`report-business report-${node.type}`}><header><b>{({kpi:"关键指标",decision:"决策判断",warning:"注意事项",stage:"阶段目标",risk:"风险提示",recommendation:"运营建议",score:"评分结果",action:"执行动作"} as Record<string,string>)[node.type]||node.type}</b><span className={`report-status ${status(node.content||"")}`}>{status(node.content||"")==="risk"?"风险":status(node.content||"")==="watch"?"观察":status(node.content||"")==="success"?"达标":"信息"}</span></header>{pairs.length?<div className="report-business-grid">{pairs.map(([key,value])=><div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div>:<div className="report-rich" dangerouslySetInnerHTML={inline(node.content)}/>}</section>}
function NodeView({node,dark}:{node:DocumentNode;dark:boolean}){if(node.type==="heading"){const Tag=(`h${node.level||2}`) as keyof JSX.IntrinsicElements;return <Tag className="report-heading" dangerouslySetInnerHTML={inline(node.content)}/>;}if(node.type==="mermaid")return <section className="report-block report-mermaid-block"><MermaidBlock code={node.content||""} theme={dark?"dark":"default"}/></section>;if(node.type==="table")return <section className="report-block report-table-wrap"><table><thead><tr>{(node.rows?.[0]||[]).map((x,i)=><th key={i} dangerouslySetInnerHTML={inline(x)}/>)}</tr></thead><tbody>{(node.rows||[]).slice(1).map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j} dangerouslySetInnerHTML={inline(x)}/>)}</tr>)}</tbody></table></section>;if(node.type==="list")return <section className="report-block"><ul>{node.items?.map((x,i)=><li key={i} dangerouslySetInnerHTML={inline(x)}/>)}</ul></section>;if(node.type==="quote")return <blockquote className="report-block" dangerouslySetInnerHTML={inline(node.content)}/>;if(node.type==="divider")return <hr/>;if(node.type==="code")return <pre className="report-block report-code"><code>{node.content}</code></pre>;if(["kpi","decision","warning","stage","risk","recommendation","score","action"].includes(node.type))return <BusinessBlock node={node}/>;return <section className="report-block report-rich" dangerouslySetInnerHTML={inline(node.content)}/>;}
export function MarkdownReportRenderer({ast,theme="ozon",mode="continuous",orientation="portrait",zoom=1,reportRef}:{ast:DocumentAst;theme?:ReportThemeName;mode?:ReportMode;orientation?:ReportOrientation;zoom?:number;reportRef?:React.Ref<HTMLDivElement>}){const dark=theme==="dark",nodes=ast.nodes.filter((node,index)=>!(index===0&&node.type==="heading"&&node.level===1&&node.content===ast.title));return <div className={`markdown-report theme-${theme} mode-${mode} orientation-${orientation}`} style={{"--report-zoom":zoom} as React.CSSProperties}><article ref={reportRef} className="report-paper"><header className="report-cover"><span>OZON OPERATIONS REPORT</span><h1>{ast.title}</h1><p>结构化 Markdown 运营报告 · {new Date().toLocaleDateString("zh-CN")}</p></header>{nodes.map(node=><NodeView node={node} dark={dark} key={node.id}/>)}</article></div>}
