import { useEffect, useMemo, useState } from "react";
import { BarChart3, ExternalLink, FileSpreadsheet, PackagePlus, Search, Store, TrendingUp } from "lucide-react";
import { addCompetitorToSelection, competitorFeishuTarget, competitorSeerfarCaptures, competitorShopNames, competitorShopProducts, importCompetitorShopExcel, openCompetitorProductUrl, saveCompetitorFeishuTarget, startCompetitorSeerfarCapture, syncCompetitorShopFeishu, testCompetitorFeishuTarget } from "./bridge";
import type { CompetitorSeerfarCapture, CompetitorShopProduct } from "./types";
import "./competitor-shop.css";

const rub=(value:number)=>`${value.toLocaleString("ru-RU",{maximumFractionDigits:0})} ₽`;
const pct=(value:number)=>`${value.toFixed(1)}%`;
export function CompetitorShopPage(){
 const [path,setPath]=useState(""),[feishuUrl,setFeishuUrl]=useState(""),[shops,setShops]=useState<string[]>([]),[shop,setShop]=useState(""),[rows,setRows]=useState<CompetitorShopProduct[]>([]),[captures,setCaptures]=useState<CompetitorSeerfarCapture[]>([]),[capturePending,setCapturePending]=useState<number|null>(null),[captureStartedAt,setCaptureStartedAt]=useState(0),[query,setQuery]=useState(""),[sort,setSort]=useState("sales"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async(nextShop=shop)=>{const names=await competitorShopNames();setShops(names);const target=nextShop||names[0]||"";setShop(target);const [products,stored]=await Promise.all([competitorShopProducts(target,query),competitorSeerfarCaptures(target)]);setRows(products);setCaptures(stored)};
 useEffect(()=>{void load().catch(e=>setMessage(String(e)));void competitorFeishuTarget().then(setFeishuUrl).catch(e=>setMessage(String(e)))},[]);
 useEffect(()=>{if(shop)void competitorShopProducts(shop,query).then(setRows).catch(e=>setMessage(String(e)))},[shop,query]);
 useEffect(()=>{if(!shop||capturePending===null)return;let active=true;let attempts=0;const poll=async()=>{try{const stored=await competitorSeerfarCaptures(shop);if(!active)return;setCaptures(stored);if(stored.some(x=>x.productId===capturePending&&Date.parse(x.capturedAt.replace(" ","T")+'Z')>=captureStartedAt-1000)){setCapturePending(null);setMessage("Seerfar 可见字段已回填到商品卡片。");return}}catch(e){if(active)setMessage(String(e))}if(++attempts>=45&&active){setCapturePending(null);setMessage("等待超时：未收到 Seerfar 可见面板数据。请确认辅助扩展已安装且面板已加载；若面板在隔离 iframe 中，当前方案无法读取。")}};void poll();const timer=setInterval(()=>void poll(),2000);return()=>{active=false;clearInterval(timer)}},[shop,capturePending,captureStartedAt]);
 const captureById=useMemo(()=>new Map(captures.map(x=>[x.productId,x])),[captures]);
 const capture=async(item:CompetitorShopProduct)=>{try{setCaptureStartedAt(Date.now());setCapturePending(item.id);setMessage(await startCompetitorSeerfarCapture(item.id))}catch(e){setCapturePending(null);setMessage(String(e))}};
 const visible=useMemo(()=>[...rows].sort((a,b)=>sort==="revenue"?b.revenue-a.revenue:sort==="growth"?b.salesGrowth-a.salesGrowth:sort==="conversion"?b.orderConversion-a.orderConversion:sort==="ad"?a.adCostShare-b.adCostShare:b.sales-a.sales),[rows,sort]);
 const totals=useMemo(()=>rows.reduce((a,x)=>({sales:a.sales+x.sales,revenue:a.revenue+x.revenue,ads:a.ads+x.estimatedAdCost}),{sales:0,revenue:0,ads:0}),[rows]);
 const importFile=async()=>{setBusy(true);setMessage("");try{const result=await importCompetitorShopExcel(path);setMessage(`导入完成：新增 ${result.imported} 个，更新 ${result.updated} 个商品。`);await load(result.shopName)}catch(e){setMessage(String(e))}finally{setBusy(false)}};
 const syncFeishu=async()=>{if(!shop)return;setBusy(true);setMessage("正在同步当前竞品店铺到飞书多维表格…");try{setMessage(await syncCompetitorShopFeishu(shop,feishuUrl))}catch(e){setMessage(String(e))}finally{setBusy(false)}};
 return <div className="competitor-shop-page"><header className="page-header"><div><span className="eyebrow">COMPETITOR STORE INTELLIGENCE</span><h1>竞品店铺拆解</h1><p>导入 Ozon 店铺 Excel，沉淀单品销量、价格、流量、转化和广告成本估算</p></div><button className="dark-button" disabled={busy||!shop||!rows.length} onClick={syncFeishu}><FileSpreadsheet/>同步当前店铺到飞书</button></header>
 <section className="card competitor-import"><FileSpreadsheet/><div><b>导入 Ozon 店铺 Excel</b><span>相同店铺与 SKU 再次导入会更新数据，不会重复建档。</span></div><input value={path} onChange={e=>setPath(e.target.value)} placeholder="粘贴 .xlsx 文件完整路径"/><button className="dark-button" disabled={busy||!path.trim()} onClick={importFile}>{busy?"导入中…":"导入并拆解"}</button></section>
 <div className="competitor-capture-note">Seerfar 浏览器补全（试验版）：需在已登录 Seerfar 的 Chrome/Edge 中自行安装项目内 <code>desktop-next/seerfar-bridge</code> 辅助扩展。点击商品的“Seerfar 补全”后仅采集可见面板；Excel 售价与插件实际售价分别保留。</div>
 <section className="card competitor-feishu-target"><FileSpreadsheet/><div><b>飞书目标多维表格</b><span>粘贴完整链接，系统自动识别 App Token 和 Table ID；View ID 不参与同步。</span></div><input value={feishuUrl} onChange={e=>setFeishuUrl(e.target.value)} placeholder="https://….feishu.cn/base/…?table=tbl…"/><div className="competitor-feishu-actions"><button disabled={!feishuUrl.trim()||busy} onClick={async()=>{try{setMessage(await testCompetitorFeishuTarget(feishuUrl))}catch(e){setMessage(String(e))}}}>测试权限</button><button disabled={!feishuUrl.trim()||busy} onClick={async()=>{try{setMessage(await saveCompetitorFeishuTarget(feishuUrl))}catch(e){setMessage(String(e))}}}>保存目标表</button></div></section>
 {message&&<div className="competitor-message">{message}</div>}
 <section className="competitor-summary"><article><Store/><span>当前竞品店铺<b>{shop||"尚未导入"}</b></span></article><article><PackagePlus/><span>商品数量<b>{rows.length}</b></span></article><article><TrendingUp/><span>总销量<b>{totals.sales.toLocaleString()}</b></span></article><article><BarChart3/><span>销售额 / 估算广告费<b>{rub(totals.revenue)} / {rub(totals.ads)}</b></span></article></section>
 <section className="card competitor-toolbar"><select value={shop} onChange={e=>setShop(e.target.value)}><option value="">选择竞品店铺</option>{shops.map(x=><option key={x}>{x}</option>)}</select><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 SKU、标题或类目"/></label><select value={sort} onChange={e=>setSort(e.target.value)}><option value="sales">按销量排序</option><option value="revenue">按销售额排序</option><option value="growth">按销量增长排序</option><option value="conversion">按转化率排序</option><option value="ad">按广告依赖从低到高</option></select></section>
 <section className="competitor-grid">{visible.map(item=>{const extra=captureById.get(item.id);return <article className="card competitor-product" key={item.id}><div className="competitor-image"><div className="competitor-image-placeholder"><Store/><span>暂无商品图</span></div>{(item.imageUrl||extra?.imageUrl)&&<img src={item.imageUrl||extra?.imageUrl} alt={item.title} onError={e=>{e.currentTarget.style.display="none"}}/>}<span>{item.fulfillment||"未知履约"}</span></div><div className="competitor-body"><header><div><small>{item.category||"未分类"} · SKU {item.sku}{item.brand?` · ${item.brand}`:""}</small><h2>{item.title}</h2></div><b>{rub(item.price)}</b></header><div className="competitor-metrics"><span>销量<b>{item.sales.toLocaleString()}</b><small>增长 {pct(item.salesGrowth)}</small></span><span>销售额<b>{rub(item.revenue)}</b><small>增长 {pct(item.revenueGrowth)}</small></span><span>毛利率<b>{pct(item.grossMargin)}</b><small>折扣 {pct(item.averageDiscount)}</small></span><span>广告费估算<b>{rub(item.estimatedAdCost)}</b><small>占比 {pct(item.adCostShare)}</small></span><span>商品访问<b>{item.productViews.toLocaleString()}</b><small>搜索加购 {pct(item.searchToCart)}</small></span><span>下单转化<b>{pct(item.orderConversion)}</b><small>曝光下单 {pct(item.impressionToOrder)}</small></span><span>退货取消<b>{pct(item.returnCancelRate)}</b><small>损失 {rub(item.lostRevenue)}</small></span><span>评价<b>{item.rating.toFixed(1)}</b><small>{item.ratingCount.toLocaleString()} 条</small></span></div><div className="competitor-funnel"><span>总曝光 {item.totalImpressions.toLocaleString()}</span><span>搜索曝光 {item.impressions.toLocaleString()}</span><span>访问加购 {pct(item.viewToCart)}</span><span>促销销量 {pct(item.promoSalesShare)}</span><span>{item.sellerType||"卖家类型未知"}</span><span>{item.salesMethod||"销售方式未知"}</span><span>{item.weightKg!==null?`${item.weightKg.toFixed(2)} kg`:"重量缺失"}</span><span>{item.launchAge||"上架时间未知"}</span></div>{extra&&<div className="competitor-seerfar"><b>Seerfar 面板 · {extra.capturedAt}</b><span>卖家实际售价 {extra.sellerPriceRub===null?"未提供":rub(extra.sellerPriceRub)}</span><span>重量 {extra.weightG===null?"未提供":`${extra.weightG} g`}</span><span>体积 {extra.dimensionsMm||"未提供"}</span><span>类目 {extra.category||"未提供"}</span><span>库存 {extra.stock===null?"未提供":extra.stock}</span><span>卖家 {extra.seller||"未提供"}</span><span>上架 {extra.listingDate||"未提供"}</span></div>}<footer><button disabled={!item.listingUrl} onClick={async()=>{try{await openCompetitorProductUrl(item.listingUrl)}catch(e){setMessage(String(e))}}}><ExternalLink/>打开商品</button><button disabled={!item.listingUrl||capturePending!==null} onClick={()=>void capture(item)}><ExternalLink/>{capturePending===item.id?"等待面板…":"Seerfar 补全"}</button><button onClick={async()=>{await addCompetitorToSelection(item.id);setMessage(`已将 SKU ${item.sku} 加入选品资料库。`)}}><PackagePlus/>加入选品库</button></footer></div></article>})}{!visible.length&&<div className="card competitor-empty">导入店铺 Excel 后，每个商品会在这里生成独立分析卡片。</div>}</section>
 </div>;
}
