import { useEffect, useMemo, useState } from "react";
import { AlertCircle, Bell, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Plus, Target, Trash2 } from "lucide-react";
import { invoke } from "@tauri-apps/api/core";
import "./daily-tasks.css";

type Task={id:number;title:string;description:string;priority:"low"|"normal"|"high"|"urgent";dueTime:string;repeatMode:"none"|"daily"|"weekdays";progress:number;status:string;note:string;overdue:boolean;dueSoon:boolean};
type Dataset={day:string;tasks:Task[];summary:{total:number;completed:number;overdue:number;progress:number}};
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const shiftDay=(value:string,amount:number)=>{const [y,m,d]=value.split("-").map(Number),date=new Date(y,m-1,d);date.setDate(date.getDate()+amount);return localDay(date)};
const empty={title:"",description:"",priority:"normal",dueTime:"18:00",repeatMode:"daily"};

export function DailyTaskCenter(){
  const [day,setDay]=useState(localDay()),[data,setData]=useState<Dataset>({day:localDay(),tasks:[],summary:{total:0,completed:0,overdue:0,progress:0}}),[form,setForm]=useState(empty),[showForm,setShowForm]=useState(false),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const call=async(command:string,id?:number,payload?:unknown)=>invoke<Dataset>("daily_task_command",{command,day,id,payload});
  const load=async()=>{try{setData(await call("list"));setMessage("")}catch(e){setMessage(String(e))}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(timer)},[day]);
  const visible=useMemo(()=>data.tasks.filter(t=>filter==="all"||filter==="open"&&t.status!=="completed"||filter==="completed"&&t.status==="completed"||filter==="overdue"&&t.overdue),[data.tasks,filter]);
  const reminders=data.tasks.filter(t=>t.overdue||t.dueSoon);
  const save=async()=>{if(!form.title.trim()){setMessage("请输入任务名称");return}setBusy(true);try{setData(await call("create",undefined,form));setForm(empty);setShowForm(false)}catch(e){setMessage(String(e))}finally{setBusy(false)}};
  const progress=async(task:Task,value:number)=>{setData(old=>({...old,tasks:old.tasks.map(t=>t.id===task.id?{...t,progress:value,status:value===100?"completed":value?"in_progress":"pending"}:t)}));try{setData(await call("progress",task.id,{progress:value,note:task.note}))}catch(e){setMessage(String(e));void load()}};
  return <div className="daily-task-page">
    <header className="task-hero"><div><span className="eyebrow"><Target size={15}/>执行与复盘</span><h1>每日任务中心</h1><p>安排今天要完成的工作，持续记录进度，并及时处理逾期事项。</p></div><button className="task-primary" onClick={()=>setShowForm(v=>!v)}><Plus size={17}/>{showForm?"收起":"新建任务"}</button></header>
    <section className="task-datebar card"><button aria-label="前一天" onClick={()=>setDay(shiftDay(day,-1))}><ChevronLeft/></button><label><CalendarDays size={17}/><input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><button aria-label="后一天" onClick={()=>setDay(shiftDay(day,1))}><ChevronRight/></button><button className="today" onClick={()=>setDay(localDay())}>回到今天</button><span>{day===localDay()?"今天":day}</span></section>
    {showForm&&<section className="card task-create"><div><label>任务名称<input autoFocus value={form.title} maxLength={100} onChange={e=>setForm({...form,title:e.target.value})} placeholder="例如：检查广告异常并完成日报"/></label><label>任务说明<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="完成标准或相关说明"/></label></div><div><label>优先级<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">低</option><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option></select></label><label>截止时间<input type="time" value={form.dueTime} onChange={e=>setForm({...form,dueTime:e.target.value})}/></label><label>重复<select value={form.repeatMode} onChange={e=>setForm({...form,repeatMode:e.target.value})}><option value="daily">每天</option><option value="weekdays">工作日</option><option value="none">仅一次</option></select></label><button disabled={busy} onClick={()=>void save()}><Check size={16}/>保存任务</button></div></section>}
    {!!reminders.length&&day===localDay()&&<section className="task-reminder"><Bell/><div><b>{reminders.length} 项任务需要注意</b><span>{reminders.slice(0,3).map(t=>`${t.title}（${t.overdue?"已逾期":`${t.dueTime} 到期`}）`).join("；")}</span></div></section>}
    <section className="task-summary-grid"><article className="card"><span>今日任务</span><strong>{data.summary.total}</strong><small>共需跟进</small></article><article className="card success"><span>已完成</span><strong>{data.summary.completed}</strong><small>{data.summary.total?Math.round(data.summary.completed/data.summary.total*100):0}% 完成率</small></article><article className="card warning"><span>已逾期</span><strong>{data.summary.overdue}</strong><small>需要优先处理</small></article><article className="card progress"><span>整体进度</span><strong>{data.summary.progress}%</strong><i><em style={{width:`${data.summary.progress}%`}}/></i></article></section>
    <section className="card task-board"><header><div><h2>任务清单</h2><p>拖动进度或点击完成，系统会按日期保留历史。</p></div><nav>{[["all","全部"],["open","进行中"],["overdue","逾期"],["completed","已完成"]].map(([id,label])=><button key={id} className={filter===id?"active":""} onClick={()=>setFilter(id)}>{label}</button>)}</nav></header>
      <div className="task-list">{visible.map(task=><article key={task.id} className={`task-item ${task.status==="completed"?"done":""} ${task.overdue?"late":""}`}><button className="task-check" onClick={()=>void progress(task,task.progress===100?0:100)}>{task.progress===100&&<Check/>}</button><div className="task-copy"><div><span className={`task-priority ${task.priority}`}>{task.priority==="urgent"?"紧急":task.priority==="high"?"高":task.priority==="low"?"低":"普通"}</span><h3>{task.title}</h3>{task.overdue&&<span className="late-label"><AlertCircle/>已逾期</span>}</div><p>{task.description||"暂无说明"}</p><small><Clock3 size={13}/>{task.dueTime} 截止 · {task.repeatMode==="daily"?"每天":task.repeatMode==="weekdays"?"工作日":"仅一次"}</small></div><div className="task-progress-control"><b>{task.progress}%</b><input aria-label={`${task.title}进度`} type="range" min="0" max="100" step="10" value={task.progress} onChange={e=>void progress(task,Number(e.target.value))}/></div><button className="task-archive" title="归档任务" onClick={async()=>{if(window.confirm(`归档任务“${task.title}”？`))setData(await call("archive",task.id))}}><Trash2/></button></article>)}{!visible.length&&<div className="task-empty"><Check/><h3>当前列表没有任务</h3><p>新建一个任务，或切换其他筛选条件。</p></div>}</div>
    </section>{message&&<div className="error-banner">{message}</div>}
  </div>
}
