import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { FileDown, FilePlus2, Image as ImageIcon, Plus, Save, Trash2, Truck } from "lucide-react";
import "./freight-quotes.css";

type Item = { imageUrl:string; productName:string; sku:string; packageLengthCm:string; packageWidthCm:string; packageHeightCm:string; unitWeightKg:string; unitsPerCarton:string; cartonLengthCm:string; cartonWidthCm:string; cartonHeightCm:string; cartonWeightKg:string; cartonCount:string; note:string };
type Form = { inquiryNo:string; title:string; route:string; destination:string; contact:string; note:string; items:Item[] };
const key="ozon-freight-quote-draft-v1", today=()=>new Date().toISOString().slice(0,10).replaceAll("-","");
const emptyItem=():Item=>({imageUrl:"",productName:"",sku:"",packageLengthCm:"",packageWidthCm:"",packageHeightCm:"",unitWeightKg:"",unitsPerCarton:"",cartonLengthCm:"",cartonWidthCm:"",cartonHeightCm:"",cartonWeightKg:"",cartonCount:"",note:""});
const blank=():Form=>({inquiryNo:`XJ-${today()}-001`,title:"物流询价",route:"中国 → 俄罗斯",destination:"",contact:"",note:"",items:[emptyItem()]});
const n=(value:string)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:0};
const fmt=(value:number,digits=2)=>value?value.toLocaleString("zh-CN",{minimumFractionDigits:digits,maximumFractionDigits:digits}):"—";

export function FreightQuotePage(){
  const [form,setForm]=useState<Form>(()=>{try{return JSON.parse(localStorage.getItem(key)||"")||blank()}catch{return blank()}}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>localStorage.setItem(key,JSON.stringify(form)),500);return()=>window.clearTimeout(timer)},[form]);
  const set=<K extends keyof Form>(field:K,value:Form[K])=>setForm(old=>({...old,[field]:value}));
  const item=(index:number,field:keyof Item,value:string)=>setForm(old=>({...old,items:old.items.map((row,i)=>i===index?{...row,[field]:value}:row)}));
  const totals=useMemo(()=>form.items.reduce((sum,row)=>{const cartons=n(row.cartonCount),quantity=n(row.unitsPerCarton)*cartons,weight=n(row.cartonWeightKg)*cartons,volume=n(row.cartonLengthCm)*n(row.cartonWidthCm)*n(row.cartonHeightCm)/1e6*cartons;return{cartons:sum.cartons+cartons,quantity:sum.quantity+quantity,weight:sum.weight+weight,volume:sum.volume+volume}}, {cartons:0,quantity:0,weight:0,volume:0}),[form.items]);
  const density=totals.volume?totals.weight/totals.volume:0;
  const save=()=>{localStorage.setItem(key,JSON.stringify(form));setMessage("配货询价草稿已保存到本机")};
  const exportExcel=async()=>{setBusy(true);setMessage("正在生成 Excel 并下载产品图片…");try{const result=await invoke<{path:string;embeddedImages:number;totalImages:number}>("freight_quote_command",{command:"export_excel",payload:form});setMessage(`Excel 已导出：${result.path}；成功嵌入 ${result.embeddedImages}/${result.totalImages} 张产品图片。`)}catch(error){setMessage(`导出失败：${String(error)}`)}finally{setBusy(false)}};
  return <div className="fq-page">
    <header className="fq-hero"><div><span>FREIGHT QUOTATION</span><h1>物流询价配货表</h1><p>整理产品包装与整票货物数据，生成带图片和公式的 Excel 发给物流商询价。</p></div><div><button onClick={()=>{setForm(blank());setMessage("已新建配货表")}}><FilePlus2/>新建</button><button onClick={save}><Save/>保存草稿</button><button className="primary" disabled={busy} onClick={()=>void exportExcel()}><FileDown/>{busy?"正在生成…":"导出 Excel"}</button></div></header>
    <section className="fq-summary">
      <div><span>总箱数</span><b>{fmt(totals.cartons,0)}</b><small>箱</small></div><div><span>总数量</span><b>{fmt(totals.quantity,0)}</b><small>件</small></div><div><span>总重</span><b>{fmt(totals.weight)}</b><small>kg</small></div><div><span>总体积</span><b>{fmt(totals.volume,3)}</b><small>m³</small></div><div><span>总密度</span><b>{fmt(density)}</b><small>kg/m³</small></div>
    </section>
    <section className="fq-card fq-meta"><div className="fq-section-title"><Truck/><div><h2>询价信息</h2><p>这些信息会写入 Excel 页首，方便物流商识别线路和批次。</p></div></div><div className="fq-meta-grid"><label>询价编号<input value={form.inquiryNo} onChange={e=>set("inquiryNo",e.target.value)}/></label><label>配货表名称<input value={form.title} onChange={e=>set("title",e.target.value)} placeholder="例如：伪装网补货"/></label><label>运输线路<input value={form.route} onChange={e=>set("route",e.target.value)} placeholder="例如：中国 → 莫斯科"/></label><label>目的地<input value={form.destination} onChange={e=>set("destination",e.target.value)}/></label><label>联系人<input value={form.contact} onChange={e=>set("contact",e.target.value)}/></label><label>询价备注<input value={form.note} onChange={e=>set("note",e.target.value)}/></label></div></section>
    <section className="fq-card"><div className="fq-products-head"><div><h2>产品明细</h2><p>黄色为输入项；蓝色为自动计算结果。图片支持 HTTPS 地址或本地绝对路径。</p></div><button onClick={()=>set("items",[...form.items,emptyItem()])}><Plus/>添加产品</button></div>
      <div className="fq-table-wrap"><table><thead><tr><th>产品图片</th><th>产品名称 / SKU</th><th>包装尺寸 cm<br/>长 / 宽 / 高</th><th>重量<br/>kg/件</th><th>装箱率<br/>件/箱</th><th>箱规 cm<br/>长 / 宽 / 高</th><th>单箱重<br/>kg</th><th>箱数</th><th>总数量<br/>件</th><th>总重<br/>kg</th><th>总体积<br/>m³</th><th>密度<br/>kg/m³</th><th>备注</th><th/></tr></thead><tbody>{form.items.map((row,index)=>{const cartons=n(row.cartonCount),quantity=n(row.unitsPerCarton)*cartons,weight=n(row.cartonWeightKg)*cartons,volume=n(row.cartonLengthCm)*n(row.cartonWidthCm)*n(row.cartonHeightCm)/1e6*cartons,rowDensity=volume?weight/volume:0;return <tr key={index}><td><div className="fq-image">{row.imageUrl?<img src={row.imageUrl} alt="产品" onError={e=>{e.currentTarget.style.display="none"}}/>:<ImageIcon/>}</div><input value={row.imageUrl} onChange={e=>item(index,"imageUrl",e.target.value)} placeholder="图片 URL / 本地路径"/></td><td><input value={row.productName} onChange={e=>item(index,"productName",e.target.value)} placeholder="产品名称"/><input value={row.sku} onChange={e=>item(index,"sku",e.target.value)} placeholder="SKU（可选）"/></td><td><Triple row={row} keys={["packageLengthCm","packageWidthCm","packageHeightCm"]} change={(k,v)=>item(index,k,v)}/></td><td><input value={row.unitWeightKg} onChange={e=>item(index,"unitWeightKg",e.target.value)}/></td><td><input value={row.unitsPerCarton} onChange={e=>item(index,"unitsPerCarton",e.target.value)}/></td><td><Triple row={row} keys={["cartonLengthCm","cartonWidthCm","cartonHeightCm"]} change={(k,v)=>item(index,k,v)}/></td><td><input value={row.cartonWeightKg} onChange={e=>item(index,"cartonWeightKg",e.target.value)}/></td><td><input value={row.cartonCount} onChange={e=>item(index,"cartonCount",e.target.value)}/></td><td className="calculated"><b>{fmt(quantity,0)}</b></td><td className="calculated"><b>{fmt(weight)}</b></td><td className="calculated"><b>{fmt(volume,3)}</b></td><td className="calculated"><b>{fmt(rowDensity)}</b></td><td><input value={row.note} onChange={e=>item(index,"note",e.target.value)}/></td><td><button className="delete" disabled={form.items.length===1} onClick={()=>set("items",form.items.filter((_,i)=>i!==index))}><Trash2/></button></td></tr>})}</tbody><tfoot><tr><td colSpan={7}>合计</td><td>{fmt(totals.cartons,0)}</td><td>{fmt(totals.quantity,0)}</td><td>{fmt(totals.weight)}</td><td>{fmt(totals.volume,3)}</td><td>{fmt(density)}</td><td colSpan={2}></td></tr></tfoot></table></div>
    </section>{message&&<div className="fq-message">{message}</div>}
  </div>
}

function Triple({row,keys,change}:{row:Item;keys:(keyof Item)[];change:(key:keyof Item,value:string)=>void}){return <div className="fq-triple">{keys.map((key,index)=><input key={key} value={row[key]} onChange={e=>change(key,e.target.value)} placeholder={["长","宽","高"][index]}/>)}</div>}
