import { useEffect, useMemo, useState } from "react";
import { BarChart3, Box, CloudUpload, RefreshCw, Settings2, Store } from "lucide-react";
import { mlAnalytics, mlDrafts, mlSettings, publishMlDraft, saveMlDraft, saveMlSettings, syncMlOrders, testMlConnection } from "./bridge";
import type { DateRange, MlAnalytics, MlDraft, MlSettingsInput } from "./types";
import "./mercadolibre.css";

type Tab = "overview" | "listing" | "analytics" | "settings";
const blankDraft = (currencyId = "MXN"): MlDraft => ({ id: null, title: "", categoryId: "", price: 0, currencyId, availableQuantity: 0, conditionCode: "new", listingTypeId: "gold_special", pictures: [], attributes: [], status: "draft", remoteItemId: "", error: "" });
const monthRange = (): DateRange => { const now = new Date(); const end = new Date(now.getFullYear(), now.getMonth() + 1, 0); const iso = (d: Date) => d.toISOString().slice(0, 10); return { from: iso(new Date(now.getFullYear(), now.getMonth(), 1)), to: iso(end) }; };

export function MercadoLibrePage() {
  const [tab, setTab] = useState<Tab>("overview"), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [settings, setSettings] = useState<MlSettingsInput>({ siteId: "MLM", sellerId: "", currencyId: "MXN", accessToken: "" });
  const [tokenConfigured, setTokenConfigured] = useState(false), [drafts, setDrafts] = useState<MlDraft[]>([]), [draft, setDraft] = useState<MlDraft>(blankDraft());
  const [picturesText, setPicturesText] = useState(""), [attributesText, setAttributesText] = useState("[]"), [range, setRange] = useState<DateRange>(monthRange), [stats, setStats] = useState<MlAnalytics | null>(null);
  const money = (value: number) => `${stats?.currencyId || settings.currencyId} ${value.toLocaleString("zh-CN", { maximumFractionDigits: 2 })}`;
  const maxRevenue = useMemo(() => Math.max(1, ...(stats?.daily.map(x => x.revenue) || [])), [stats]);
  const reload = async () => { const [s, rows, report] = await Promise.all([mlSettings(), mlDrafts(), mlAnalytics(range)]); setSettings({ siteId: s.siteId, sellerId: s.sellerId, currencyId: s.currencyId, accessToken: "" }); setTokenConfigured(s.tokenConfigured); setDrafts(rows); setStats(report); };
  useEffect(() => { reload().catch(e => setMessage(String(e))); }, []);
  const run = async (work: () => Promise<unknown>, success: string) => { setBusy(true); setMessage(""); try { await work(); setMessage(success); await reload(); } catch (e) { setMessage(String(e)); } finally { setBusy(false); } };
  const edit = (row: MlDraft) => { setDraft(row); setPicturesText(row.pictures.join("\n")); setAttributesText(JSON.stringify(row.attributes, null, 2)); setTab("listing"); };
  const saveDraft = () => run(async () => { const attributes = JSON.parse(attributesText); await saveMlDraft({ ...draft, currencyId: settings.currencyId, pictures: picturesText.split(/\r?\n/).map(x => x.trim()).filter(Boolean), attributes }); setDraft(blankDraft(settings.currencyId)); setPicturesText(""); setAttributesText("[]"); }, "上架草稿已保存。");
  const publish = (row: MlDraft) => { if (!row.id || !window.confirm(`确认将“${row.title}”真实发布到美客多？`)) return; void run(() => publishMlDraft(row.id!), "商品已发布到美客多。"); };
  return <div className="ml-page">
    <header className="ml-header"><div><span>MERCADO LIBRE WORKSPACE</span><h1>美客多独立工作台</h1><p>独立账户、独立数据库；覆盖商品上架、订单同步与经营分析</p></div><div className="ml-status">{tokenConfigured ? "API 已配置" : "待配置 API"}</div></header>
    <nav className="ml-tabs">{([["overview","经营总览",Store],["listing","产品上架",CloudUpload],["analytics","订单与分析",BarChart3],["settings","API 设置",Settings2]] as const).map(([key,label,Icon]) => <button key={key} className={tab===key?"active":""} onClick={() => setTab(key)}><Icon size={16}/>{label}</button>)}</nav>
    {message && <div className={`ml-message ${message.includes("失败") || message.includes("Error") ? "error" : ""}`}>{message}</div>}
    {tab === "overview" && <><section className="ml-kpis"><article><small>上架草稿</small><b>{drafts.filter(x=>x.status!=="published").length}</b></article><article><small>已发布商品</small><b>{drafts.filter(x=>x.status==="published").length}</b></article><article><small>本期订单</small><b>{stats?.orders || 0}</b></article><article><small>本期销售额</small><b>{money(stats?.revenue || 0)}</b></article></section><section className="ml-panel"><h2>开始使用</h2><div className="ml-flow"><div><Settings2/>配置卖家 ID 与 OAuth Token</div><i>→</i><div><CloudUpload/>建立并发布商品草稿</div><i>→</i><div><RefreshCw/>同步订单并查看分析</div></div><p className="ml-note">当前不会生成模拟销售数据；总览仅展示独立美客多数据库中真实同步的订单。</p></section></>}
    {tab === "listing" && <><section className="ml-panel"><h2>{draft.id ? "编辑上架草稿" : "新建上架草稿"}</h2><div className="ml-form ml-grid"><label>标题<input value={draft.title} maxLength={60} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>叶子类目 ID<input value={draft.categoryId} placeholder="例如 MLM1234" onChange={e=>setDraft({...draft,categoryId:e.target.value})}/></label><label>售价（{settings.currencyId}）<input type="number" min="0" value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></label><label>库存<input type="number" min="0" value={draft.availableQuantity} onChange={e=>setDraft({...draft,availableQuantity:Number(e.target.value)})}/></label><label>商品成色<select value={draft.conditionCode} onChange={e=>setDraft({...draft,conditionCode:e.target.value as MlDraft["conditionCode"]})}><option value="new">全新</option><option value="used">二手</option><option value="not_specified">未指定</option></select></label><label>刊登类型<select value={draft.listingTypeId} onChange={e=>setDraft({...draft,listingTypeId:e.target.value})}><option value="gold_special">gold_special</option><option value="gold_pro">gold_pro</option><option value="free">free</option></select></label><label className="wide">图片 URL（每行一个）<textarea rows={4} value={picturesText} onChange={e=>setPicturesText(e.target.value)}/></label><label className="wide">商品属性 JSON 数组<textarea rows={6} value={attributesText} onChange={e=>setAttributesText(e.target.value)}/></label></div><button className="ml-primary" disabled={busy} onClick={saveDraft}>{busy?"处理中…":"保存草稿"}</button></section><section className="ml-panel"><h2>上架任务</h2><div className="ml-table"><table><thead><tr><th>商品</th><th>类目</th><th>售价/库存</th><th>状态</th><th>操作</th></tr></thead><tbody>{drafts.map(row=><tr key={row.id}><td><b>{row.title}</b>{row.remoteItemId&&<small>{row.remoteItemId}</small>}</td><td>{row.categoryId}</td><td>{row.currencyId} {row.price} / {row.availableQuantity}</td><td><span className={`ml-badge ${row.status}`}>{row.status}</span>{row.error&&<small className="ml-error">{row.error}</small>}</td><td><button onClick={()=>edit(row)}>编辑</button><button disabled={busy||row.status==="published"} onClick={()=>publish(row)}>发布</button></td></tr>)}</tbody></table>{!drafts.length&&<div className="ml-empty">还没有上架草稿</div>}</div></section></>}
    {tab === "analytics" && <><section className="ml-toolbar"><label>开始<input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></label><label>结束<input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></label><button disabled={busy} onClick={()=>run(()=>syncMlOrders(range),"订单同步完成。")}>同步真实订单</button><button onClick={()=>run(async()=>setStats(await mlAnalytics(range)),"分析已刷新。")}>刷新分析</button></section><section className="ml-kpis"><article><small>订单</small><b>{stats?.orders||0}</b></article><article><small>销量</small><b>{stats?.units||0}</b></article><article><small>销售额</small><b>{money(stats?.revenue||0)}</b></article><article><small>平均客单价</small><b>{stats?.averageOrderValue==null?"—":money(stats.averageOrderValue)}</b></article></section><section className="ml-panel"><h2>每日销售趋势</h2><div className="ml-bars">{stats?.daily.map(x=><div key={x.day} title={`${x.day} · ${money(x.revenue)} · ${x.units} 件`}><span style={{height:`${Math.max(3,x.revenue/maxRevenue*100)}%`}}/><small>{x.day.slice(5)}</small></div>)}</div>{!stats?.daily.length&&<div className="ml-empty">当前日期范围尚无已同步订单</div>}</section></>}
    {tab === "settings" && <section className="ml-panel"><h2>美客多 API 设置</h2><p className="ml-note">Token 使用 Windows 本机加密保存；留空可保留现有 Token。数据写入独立的 mercadolibre.db。</p><div className="ml-form ml-grid"><label>站点<select value={settings.siteId} onChange={e=>setSettings({...settings,siteId:e.target.value,currencyId:e.target.selectedOptions[0].dataset.currency||"MXN"})}><option value="MLM" data-currency="MXN">墨西哥 MLM</option><option value="MLB" data-currency="BRL">巴西 MLB</option><option value="MLA" data-currency="ARS">阿根廷 MLA</option><option value="MCO" data-currency="COP">哥伦比亚 MCO</option><option value="MLC" data-currency="CLP">智利 MLC</option><option value="MPE" data-currency="PEN">秘鲁 MPE</option></select></label><label>币种<input value={settings.currencyId} onChange={e=>setSettings({...settings,currencyId:e.target.value.toUpperCase()})}/></label><label>卖家 ID<input value={settings.sellerId} onChange={e=>setSettings({...settings,sellerId:e.target.value})}/></label><label>OAuth Access Token<input type="password" placeholder={tokenConfigured?"已配置；留空保持不变":"请输入 Token"} value={settings.accessToken} onChange={e=>setSettings({...settings,accessToken:e.target.value})}/></label></div><div className="ml-actions"><button className="ml-primary" disabled={busy} onClick={()=>run(()=>saveMlSettings(settings),"API 设置已保存。")}>保存设置</button><button disabled={busy} onClick={()=>run(async()=>{await saveMlSettings(settings); const text=await testMlConnection(); setMessage(text);},"连接成功。")}>保存并测试连接</button></div></section>}
  </div>;
}
