import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { AlertTriangle, BadgeRussianRuble, CheckCircle2, History, RefreshCw, ShieldCheck, Tags } from "lucide-react";
import "./price-promotion-center.css";

type Shop={id:string;name:string;status:string};
type Row={listingId:string;skuId?:string;sku?:string;name?:string;nmId:string;mappingStatus:string;basePrice?:string;discountPct?:string;effectivePrice?:string;currency:string;observedAt?:string;dataStatus:string;minimumSafePrice?:string};
type Guard={status:"safe"|"warning"|"blocked"|"insufficient_data";currentPrice?:string;proposedPrice:string;minimumSafePrice?:string;estimatedMarginPct?:string;estimatedProfitPerUnit?:string;reasons:string[];costDataStatus:string};
type Job={id:string;changeId:string;status:string;successCount:number;failedCount:number;blockedCount:number;createdAt:string;reason?:string};
type Promotion={id:string;externalPromotionId:string;name:string;startsAt?:string;endsAt?:string;status:string;dataStatus:string};
type Data={rows:Row[];history:any[];jobs:Job[];promotions:Promotion[]};
const call=<T,>(action:string,payload:Record<string,unknown>={})=>invoke<T>("price_center",{action,payload});
const shopCall=<T,>(action:string,payload?:Record<string,unknown>)=>invoke<T>("wb_shop_center",{action,payload});
const label:Record<string,string>={safe:"安全",warning:"提醒",blocked:"已阻止",insufficient_data:"成本不足",complete:"完整",partial:"部分",missing:"缺失",stale:"过期",pending:"待处理",success:"成功",failed:"失败",active:"进行中",upcoming:"即将开始",ended:"已结束"};
function Status({value}:{value:string}){return <span className={`pp-status ${value}`}>{label[value]||value}</span>}

export function PricePromotionCenter(){
 const [shops,setShops]=useState<Shop[]>([]),[shopId,setShopId]=useState(""),[data,setData]=useState<Data>({rows:[],history:[],jobs:[],promotions:[]});
 const [tab,setTab]=useState("overview"),[busy,setBusy]=useState(""),[error,setError]=useState(""),[note,setNote]=useState("");
 const [selected,setSelected]=useState<Record<string,boolean>>({}),[mode,setMode]=useState("decrease"),[amount,setAmount]=useState("5"),[reason,setReason]=useState(""),[preview,setPreview]=useState<Array<Row&{proposedPrice:string;guard:Guard}>>([]);
 const load=async(id=shopId)=>{if(!id)return;setBusy("load");setError("");try{setData(await call<Data>("dashboard",{shopId:id}))}catch(e){setError(String(e))}finally{setBusy("")}};
 useEffect(()=>{shopCall<{shops:Shop[]}>("dashboard").then(x=>{setShops(x.shops);if(x.shops[0])setShopId(x.shops[0].id)}).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(shopId)load(shopId)},[shopId]);
 const cards=useMemo(()=>{let safe=0,risk=0,missing=0,stale=0;for(const r of data.rows){if(!r.basePrice)missing++;else if(r.minimumSafePrice&&Number(r.basePrice)<Number(r.minimumSafePrice))risk++;else safe++;if(r.observedAt&&Date.now()-Date.parse(r.observedAt)>24*3600e3)stale++}return {total:data.rows.length,safe,risk,missing,stale}},[data.rows]);
 const sync=async(action:string)=>{setBusy(action);setError("");try{const x=await call<{records:number}>(action,{shopId});setNote(`同步完成：${x.records} 条记录`);await load()}catch(e){setError(String(e))}finally{setBusy("")}};
 const calculate=async()=>{setBusy("preview");setError("");try{const chosen=data.rows.filter(r=>selected[r.listingId]&&r.basePrice);const out=[] as Array<Row&{proposedPrice:string;guard:Guard}>;for(const r of chosen){const current=Number(r.basePrice);const proposed=mode==="absolute"?Number(amount):mode==="increase"?current*(1+Number(amount)/100):current*(1-Number(amount)/100);const proposedPrice=proposed.toFixed(2);const guard=await call<Guard>("preview",{shopId,listingId:r.listingId,proposedPrice});out.push({...r,proposedPrice,guard})}setPreview(out);if(!out.length)setError("请选择至少一个已有当前价格的 SKU") }catch(e){setError(String(e))}finally{setBusy("")}};
 const execute=async()=>{if(!reason.trim()){setError("执行改价必须填写原因");return}const executable=preview.filter(x=>x.guard.status==="safe"||x.guard.status==="warning");if(!executable.length){setError("预览中没有可执行项目");return}if(!confirm(`确认向 Wildberries 提交 ${executable.length} 个价格？平台返回成功后仍需再次同步验证。`))return;setBusy("execute");setError("");try{const x=await call<any>("execute",{shopId,mode:"bulk",reason,items:executable.map(x=>({listingId:x.listingId,proposedPrice:x.proposedPrice}))});setNote(`已提交：${x.submitted||0}，阻止：${x.blocked||0}。请稍后同步价格完成验证。`);setPreview([]);await load()}catch(e){setError(String(e))}finally{setBusy("")}};
 const tabs=[["overview","价格总览"],["sku","SKU 价格"],["bulk","批量改价"],["rules","最低安全价"],["promotions","活动中心"],["history","价格历史"],["jobs","改价任务"]];
 return <div className="pp-page">
  <header className="pp-header"><div><span>WILDBERRIES ERP · PRICE CONTROL</span><h1>价格与活动中心</h1><p>价格事实、安全校验、批量执行、活动判断与审计</p></div><div className="pp-actions"><select value={shopId} onChange={e=>setShopId(e.target.value)}>{shops.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={()=>sync("sync_prices")} disabled={!!busy}><RefreshCw size={16}/>同步价格</button><button onClick={()=>sync("sync_promotions")} disabled={!!busy}><Tags size={16}/>同步活动</button></div></header>
  {error&&<div className="pp-banner error"><AlertTriangle size={18}/>{error}</div>}{note&&<div className="pp-banner ok"><CheckCircle2 size={18}/>{note}</div>}
  <nav className="pp-tabs">{tabs.map(([k,v])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{v}</button>)}</nav>
  {(tab==="overview")&&<><section className="pp-kpis"><article><BadgeRussianRuble/><b>{cards.total}</b><span>价格 SKU</span></article><article><ShieldCheck/><b>{cards.safe}</b><span>安全</span></article><article className="warn"><AlertTriangle/><b>{cards.risk}</b><span>低于安全价</span></article><article><b>{cards.missing}</b><span>无价格数据</span></article><article><b>{cards.stale}</b><span>超过 24 小时</span></article></section><PriceTable rows={data.rows}/></>}
  {tab==="sku"&&<PriceTable rows={data.rows}/>} 
  {tab==="bulk"&&<section className="pp-panel"><h2>批量改价</h2><div className="pp-form"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="decrease">按百分比降价</option><option value="increase">按百分比涨价</option><option value="absolute">统一绝对价格</option></select><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/><input className="reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="改价原因（必填）"/><button onClick={calculate} disabled={busy==="preview"}>生成安全预览</button></div><table><thead><tr><th></th><th>SKU</th><th>当前价</th><th>新价格</th><th>最低安全价</th><th>预计利润*</th><th>Guard</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.listingId}><td><input type="checkbox" checked={!!selected[r.listingId]} onChange={e=>setSelected({...selected,[r.listingId]:e.target.checked})}/></td><td>{r.sku||r.nmId}</td><td>{r.basePrice||"—"}</td><td colSpan={4}>选择后生成预览</td></tr>)}</tbody></table>{preview.length>0&&<div className="pp-preview"><h3>执行前预览</h3><table><tbody>{preview.map(x=><tr key={x.listingId}><td>{x.sku||x.nmId}</td><td>{x.basePrice} → <b>{x.proposedPrice}</b></td><td>{x.guard.minimumSafePrice||"—"}</td><td>{x.guard.estimatedProfitPerUnit||"—"}</td><td><Status value={x.guard.status}/><small>{x.guard.reasons.join("；")}</small></td></tr>)}</tbody></table><p>* 当前利润只扣已知采购成本；成本不完整时状态不会显示为安全。</p><button className="primary" onClick={execute} disabled={!!busy}>确认并提交可执行项</button></div>}</section>}
  {tab==="rules"&&<RulePanel shopId={shopId} rows={data.rows} done={()=>load()}/>} 
  {tab==="promotions"&&<section className="pp-panel"><h2>活动中心 <small>平台同步；参与写入暂不开放</small></h2><table><thead><tr><th>活动</th><th>开始</th><th>结束</th><th>状态</th><th>数据</th></tr></thead><tbody>{data.promotions.map(x=><tr key={x.id}><td><b>{x.name}</b><small>ID {x.externalPromotionId}</small></td><td>{x.startsAt||"—"}</td><td>{x.endsAt||"—"}</td><td><Status value={x.status}/></td><td><Status value={x.dataStatus}/></td></tr>)}</tbody></table>{!data.promotions.length&&<Empty text="暂无活动数据，请从 Wildberries 同步。"/>}</section>}
  {tab==="history"&&<section className="pp-panel"><h2><History size={18}/>价格历史（追加保存）</h2><table><thead><tr><th>时间</th><th>Listing</th><th>原价</th><th>折扣</th><th>有效价</th><th>来源</th></tr></thead><tbody>{data.history.map(x=><tr key={x.id}><td>{x.observedAt}</td><td>{x.listingId}</td><td>{x.basePrice??"—"}</td><td>{x.discountPct==null?"—":`${x.discountPct}%`}</td><td>{x.effectivePrice??"—"}</td><td>{x.changeType}</td></tr>)}</tbody></table></section>}
  {tab==="jobs"&&<section className="pp-panel"><h2>改价任务</h2><table><thead><tr><th>时间</th><th>任务</th><th>状态</th><th>成功</th><th>失败</th><th>阻止</th><th>原因</th></tr></thead><tbody>{data.jobs.map(x=><tr key={x.id}><td>{x.createdAt}</td><td>{x.changeId}</td><td><Status value={x.status}/></td><td>{x.successCount}</td><td>{x.failedCount}</td><td>{x.blockedCount}</td><td>{x.reason||"—"}</td></tr>)}</tbody></table></section>}
 </div>
}
function Empty({text}:{text:string}){return <div className="pp-empty">{text}</div>}
function PriceTable({rows}:{rows:Row[]}){return <section className="pp-panel"><h2>当前价格事实</h2><table><thead><tr><th>SKU / 商品</th><th>nmID</th><th>映射</th><th>平台原价</th><th>折扣</th><th>有效价</th><th>最低安全价</th><th>数据状态</th><th>最后同步</th></tr></thead><tbody>{rows.map(r=><tr key={r.listingId}><td><b>{r.sku||"未映射"}</b><small>{r.name||r.listingId}</small></td><td>{r.nmId}</td><td><Status value={r.mappingStatus.toLowerCase()}/></td><td>{r.basePrice??"—"} {r.basePrice&&r.currency}</td><td>{r.discountPct==null?"—":`${r.discountPct}%`}</td><td>{r.effectivePrice??"—"}</td><td>{r.minimumSafePrice??"未配置"}</td><td><Status value={r.dataStatus}/></td><td>{r.observedAt||"从未同步"}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No price data. Sync prices from Wildberries."/>}</section>}
function RulePanel({shopId,rows,done}:{shopId:string;rows:Row[];done:()=>void}){const[skuId,setSku]=useState(""),[minimum,setMinimum]=useState(""),[rounding,setRounding]=useState("none"),[message,setMessage]=useState("");const save=async()=>{try{await call("save_rule",{shopId,skuId:skuId||null,minimumSafePrice:minimum||null,roundingRule:rounding});setMessage("安全规则已保存");done()}catch(e){setMessage(String(e))}};return <section className="pp-panel"><h2>最低安全价规则</h2><p>规则优先级：SKU → SPU → 店铺 → 组织。当前阶段可配置明确的最低安全价；完整自动反推等待财务成本模块。</p><div className="pp-form"><select value={skuId} onChange={e=>setSku(e.target.value)}><option value="">店铺默认规则</option>{rows.filter(x=>x.skuId).map(x=><option value={x.skuId} key={x.listingId}>{x.sku||x.nmId}</option>)}</select><input placeholder="最低安全价 RUB" value={minimum} onChange={e=>setMinimum(e.target.value)}/><select value={rounding} onChange={e=>setRounding(e.target.value)}><option value="none">不取整</option><option value="integer">整数</option><option value="end_90">尾数 90</option><option value="end_99">尾数 99</option></select><button onClick={save}>保存规则</button></div>{message&&<p>{message}</p>}</section>}
