import { type CSSProperties, type ReactNode, useDeferredValue, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CalendarDays, CheckCircle2, Database, Gauge, Link2, MapPinned, Package, Search, ShieldAlert, ShoppingCart, Target, TrendingUp, WalletCards, X } from "lucide-react";
import { productAnalysis, productDetail, saveProductSeries, seriesInsights } from "./bridge";
import type { InsightRow, ProductAnalysisRow, ProductDetail } from "./types";
import { adjustedScore, buildDecisionProfiles, type DecisionProfile } from "./product-decision-engine";
import "./product-analysis.css";
import "./product-analysis-modal.css";

const localDay = (date: Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const previousCompleteDay = () => { const d=new Date(); d.setDate(d.getDate()-1); return localDay(d); };
const parseDay=(value:string)=>{const [y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d);};
const addDays=(value:string,amount:number)=>{const d=parseDay(value);d.setDate(d.getDate()+amount);return localDay(d);};
const dayCount=(from:string,to:string)=>Math.max(1,Math.round((parseDay(to).getTime()-parseDay(from).getTime())/86400000)+1);
const listDays=(from:string,to:string)=>Array.from({length:dayCount(from,to)},(_,i)=>addDays(from,i));
type AnalysisMode="week"|"month"|"range";
type AnalysisPeriod={from:string;to:string};
const resolvePeriod=(mode:AnalysisMode,end:string,start:string):AnalysisPeriod=>{const ceiling=previousCompleteDay(),to=end>ceiling?ceiling:end;if(mode==="week")return{from:addDays(to,-6),to};if(mode==="month")return{from:`${to.slice(0,7)}-01`,to};return{from:start>to?to:start,to};};
const previousPeriod=(period:AnalysisPeriod):AnalysisPeriod=>{const days=dayCount(period.from,period.to),to=addDays(period.from,-1);return{from:addDays(to,-days+1),to};};
const n = (v:number|null, suffix="") => v==null ? "—" : `${v.toLocaleString("zh-CN",{maximumFractionDigits:2})}${suffix}`;
const tone = (score:number) => score>=85?"excellent":score>=70?"good":score>=55?"watch":"risk";

function ScoreRing({score,grade}:{score:number;grade:string}) {
  return <div className={`score-ring ${tone(score)}`} style={{"--score":score} as CSSProperties}><div><strong>{score}</strong><span>{grade}</span></div></div>;
}
function ScoreBar({label,score,max}:{label:string;score:number;max:number}) {
  const pct=Math.round(score/max*100);
  return <div className="score-bar"><div><span>{label}</span><b>{score}/{max}</b></div><i><em style={{width:`${pct}%`}} /></i></div>;
}
type ModalState={title:string;subtitle:string;content:ReactNode}|null;
const RawRows=({rows}:{rows:Array<[string,string|number]>})=><div className="raw-data-list">{rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div>;

function aggregatePeriod(currentSets:ProductAnalysisRow[][],previousSets:ProductAnalysisRow[][],period:AnalysisPeriod):ProductAnalysisRow[]{
  const grouped=new Map<string,ProductAnalysisRow[]>(),previous=new Map<string,ProductAnalysisRow[]>();
  currentSets.flat().forEach(r=>grouped.set(r.sku,[...(grouped.get(r.sku)||[]),r]));previousSets.flat().forEach(r=>previous.set(r.sku,[...(previous.get(r.sku)||[]),r]));
  const sum=(items:ProductAnalysisRow[])=>items.reduce((a,r)=>({impressions:a.impressions+r.impressions,clicks:a.clicks+r.clicks,adOrders:a.adOrders+r.adOrders,adRevenue:a.adRevenue+r.adRevenue,adSpend:a.adSpend+r.adSpend,totalUnits:a.totalUnits+r.totalUnits,totalRevenue:a.totalRevenue+r.totalRevenue}),{impressions:0,clicks:0,adOrders:0,adRevenue:0,adSpend:0,totalUnits:0,totalRevenue:0});
  const ratio=(a:number,b:number)=>b>0?a/b:null,days=dayCount(period.from,period.to);
  return [...grouped.entries()].map(([sku,items])=>{const latest=items.at(-1)!,c=sum(items),p=sum(previous.get(sku)||[]),ctr=ratio(c.clicks*100,c.impressions),cpc=ratio(c.adSpend,c.clicks),cvr=ratio(c.adOrders*100,c.clicks),cpa=ratio(c.adSpend,c.adOrders),roas=ratio(c.adRevenue,c.adSpend),incrementalRoas=c.adSpend-p.adSpend>0?(c.adRevenue-p.adRevenue)/(c.adSpend-p.adSpend):null,inventoryDays=c.totalUnits>0?latest.stock/(c.totalUnits/days):null;
    const trafficScore=ctr==null?0:ctr>=3?20:ctr>=2?16:ctr>=1?10:5,conversionScore=c.clicks<20?8:cvr==null?0:cvr>=8?20:cvr>=5?16:cvr>=3?12:cvr>=1?6:2,profitScore=c.adSpend<=0?15:latest.cpaLimit==null||cpa==null?6:cpa<=latest.cpaLimit?25:cpa<=latest.cpaLimit*1.2?16:cpa<=latest.cpaLimit*1.5?9:2,inventoryScore=inventoryDays==null?3:inventoryDays>=14&&inventoryDays<=60?15:inventoryDays>=7&&inventoryDays<=90?10:inventoryDays>90?4:2,sampleReady=days>=3&&c.clicks>=100,scaleScore=!sampleReady?8:incrementalRoas!=null&&latest.breakEvenRoas!=null&&incrementalRoas>=latest.breakEvenRoas?20:incrementalRoas!=null&&latest.breakEvenRoas!=null&&incrementalRoas>=latest.breakEvenRoas*.8?12:4,overallScore=trafficScore+conversionScore+profitScore+inventoryScore+scaleScore,grade=overallScore>=85?"优秀":overallScore>=70?"良好":overallScore>=55?"观察":"风险";
    const diagnosis=c.clicks>=20&&(cvr??0)<3?"CVR 偏低":latest.cpaLimit!=null&&cpa!=null&&cpa>latest.cpaLimit?"广告获客成本超限":inventoryDays!=null&&inventoryDays>90?"库存周转偏慢":overallScore>=70?"经营状态良好":"需要继续观察",action=!sampleReady?"继续积累完整周期样本，达到 3 天且累计 100 点击后再做强判断":diagnosis==="CVR 偏低"?"只修改图片、价格或页面信息中的一个变量并观察":diagnosis==="广告获客成本超限"?"降低低效投放并核对贡献利润安全线":diagnosis==="库存周转偏慢"?"控制补货并优先去库存":"保持单变量测试，按等长前期验证增量";
    return{...latest,day:`${period.from} ~ ${period.to}`,ruleVersion:"product-analysis-v2.2.0",impressions:c.impressions,clicks:c.clicks,ctr,cpc,adOrders:c.adOrders,adRevenue:c.adRevenue,adSpend:c.adSpend,cvr,cpa,roas,totalUnits:c.totalUnits,totalRevenue:c.totalRevenue,inventoryDays,clicks3d:c.clicks,units7d:c.totalUnits,previousUnits7d:p.totalUnits,revenue7d:c.totalRevenue,previousRevenue7d:p.totalRevenue,adSpend7d:c.adSpend,previousAdSpend7d:p.adSpend,adOrders7d:c.adOrders,previousAdOrders7d:p.adOrders,adRevenue7d:c.adRevenue,previousAdRevenue7d:p.adRevenue,incrementalRoas,trafficScore,conversionScore,profitScore,inventoryScore,scaleScore,overallScore,grade,sampleReady,diagnosis,action,confidence:latest.cpaLimit!=null&&c.clicks>=100?"高":c.clicks>=30?"中":"低",adSource:`${latest.adSource}；按所选完整自然日周期汇总`};}).sort((a,b)=>b.totalRevenue-a.totalRevenue||b.overallScore-a.overallScore);
}

export function ProductAnalysisPage({currency}:{currency:string}) {
  const [mode,setMode]=useState<AnalysisMode>("week"),[endDay,setEndDay]=useState(previousCompleteDay),[startDay,setStartDay]=useState(addDays(previousCompleteDay(),-6)),[query,setQuery]=useState(""),[rows,setRows]=useState<ProductAnalysisRow[]>([]),
    [selected,setSelected]=useState<Set<string>>(new Set()),[focusedSku,setFocusedSku]=useState(""),[series,setSeries]=useState<InsightRow[]>([]),
    [profiles,setProfiles]=useState<Map<string,DecisionProfile>>(new Map()),[modal,setModal]=useState<ModalState>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const deferred=useDeferredValue(query);
  const period=useMemo(()=>resolvePeriod(mode,endDay,startDay),[mode,endDay,startDay]),comparison=useMemo(()=>previousPeriod(period),[period.from,period.to]),periodDays=dayCount(period.from,period.to),day=period.to,periodText=`${period.from} 至 ${period.to}`;
  const load=async()=>{const currentDays=listDays(period.from,period.to),previousDays=listDays(comparison.from,comparison.to),historyDays=listDays(addDays(period.to,-29),period.to),allDays=[...new Set([...currentDays,...previousDays,...historyDays])],[sets,groups]=await Promise.all([Promise.all(allDays.map(async d=>[d,await productAnalysis(d,deferred)] as const)),seriesInsights(period.to)]),byDay=new Map(sets),current=currentDays.map(d=>byDay.get(d)||[]),previous=previousDays.map(d=>byDay.get(d)||[]),history=historyDays.map(d=>byDay.get(d)||[]),data=aggregatePeriod(current,previous,period),previousData=aggregatePeriod(previous,[],comparison),detailEntries=await Promise.all(data.map(async r=>{try{return[r.sku,await productDetail(r.sku,period.to)] as const}catch{return null}})),details=new Map<string,ProductDetail>(detailEntries.filter((x):x is readonly [string,ProductDetail]=>x!=null));setRows(data);setProfiles(buildDecisionProfiles(history,data,previousData,details,period));setSeries(groups);setFocusedSku(old=>data.some(r=>r.sku===old)?old:(data[0]?.sku||""));setSelected(old=>new Set([...old].filter(s=>data.some(r=>r.sku===s))));};
  useEffect(()=>{setBusy(true);setMessage("");load().catch(e=>setMessage(String(e))).finally(()=>setBusy(false));},[period.from,period.to,comparison.from,comparison.to,deferred]);
  const focus=rows.find(r=>r.sku===focusedSku)||rows[0];
  const profile=focus?profiles.get(focus.sku):undefined;
  const scoped=selected.size?rows.filter(r=>selected.has(r.sku)):rows;
  const total=useMemo(()=>scoped.reduce((a,r)=>({units:a.units+r.totalUnits,revenue:a.revenue+r.totalRevenue,ad:a.ad+r.adSpend,adRevenue:a.adRevenue+r.adRevenue,stock:a.stock+r.stock}),{units:0,revenue:0,ad:0,adRevenue:0,stock:0}),[scoped]);
  const linkedRows=useMemo(()=>{
    if(selected.size>=2)return scoped;
    const saved=series.find(g=>focus&&g.skus.includes(focus.sku));
    return saved?rows.filter(r=>saved.skus.includes(r.sku)):(focus?[focus]:[]);
  },[selected,scoped,series,focus,rows]);
  const linkDecision=useMemo(()=>{
    const current=linkedRows.reduce((s,r)=>s+r.units7d,0),previous=linkedRows.reduce((s,r)=>s+r.previousUnits7d,0);
    const change=previous>0?(current-previous)/previous*100:null;
    const totalClicks=linkedRows.reduce((s,r)=>s+r.clicks,0),totalImpressions=linkedRows.reduce((s,r)=>s+r.impressions,0),totalOrders=linkedRows.reduce((s,r)=>s+r.adOrders,0),totalSpend=linkedRows.reduce((s,r)=>s+r.adSpend,0),totalAdRevenue=linkedRows.reduce((s,r)=>s+r.adRevenue,0),demandScore=change==null?50:Math.max(0,Math.min(100,50+change*2)),trafficScore=totalImpressions>0?Math.min(100,totalClicks/totalImpressions*100/3*100):0,conversionScore=totalClicks>0?Math.min(100,totalOrders/totalClicks*100/8*100):0,profitRows=linkedRows.filter(r=>r.cpaLimit!=null&&r.cpa!=null),profitScore=profitRows.length?profitRows.reduce((s,r)=>s+Math.min(100,(r.cpaLimit!/Math.max(.01,r.cpa!))*100),0)/profitRows.length:null,supplyScore=linkedRows.reduce((s,r)=>s+(r.inventoryDays!=null&&r.inventoryDays>=21?100:r.inventoryDays!=null?Math.min(100,r.inventoryDays/21*100):0),0)/Math.max(1,linkedRows.length),knownWeight=.25+.15+.15+(profitScore==null?0:.20)+.10,health=Math.round((demandScore*.25+trafficScore*.15+conversionScore*.15+(profitScore??0)*.20+supplyScore*.10)/knownWeight);
    const migrations=linkedRows.map(r=>{const loss=Math.max(0,r.previousUnits7d-r.units7d),gain=linkedRows.filter(x=>x.sku!==r.sku).reduce((s,x)=>s+Math.max(0,x.units7d-x.previousUnits7d),0),decline=r.previousUnits7d>0?(r.units7d-r.previousUnits7d)/r.previousUnits7d*100:null,carry=loss>0?gain/loss*100:0;return{sku:r.sku,offer:r.offerId||r.sku,decline,carry,isMigration:decline!=null&&decline<=-20&&change!=null&&change>=-10&&carry>=60};});
    const migrated=migrations.find(x=>x.isMigration);
    const status=migrated?"疑似变体迁移":change==null?"历史样本不足":change>=8?"链接增长":change<=-10?"链接下滑":"链接稳定";
    const maxCvr=Math.max(.01,...linkedRows.map(r=>r.cvr??0)),maxClicks=Math.max(1,...linkedRows.map(r=>r.clicks)),maxMargin=Math.max(.01,...linkedRows.map(r=>r.cpaLimit??0)),minPrice=Math.min(...linkedRows.map(r=>r.price??Infinity));
    const variants=linkedRows.map(r=>{const p=profiles.get(r.sku),absoluteConversion=Math.min(100,(r.cvr??0)/8*100),absoluteTraffic=Math.min(100,r.clicks/200*100),absoluteProfit=r.cpaLimit==null?null:Math.min(100,r.cpaLimit/Math.max(1,r.price??r.cpaLimit)*250),absoluteLocalization=p?.lsi??null,absolutePrice=r.price?Math.min(100,minPrice/r.price*100):null,absoluteInventory=r.inventoryDays==null?null:r.inventoryDays>=21&&r.inventoryDays<=60?100:r.inventoryDays<21?r.inventoryDays/21*100:Math.max(20,100-(r.inventoryDays-60)),relativeConversion=Math.min(100,(r.cvr??0)/maxCvr*100),relativeTraffic=Math.min(100,r.clicks/maxClicks*100),relativeProfit=Math.min(100,(r.cpaLimit??0)/maxMargin*100),combine=(absolute:number|null,relative:number)=>absolute==null?relative:absolute*.7+relative*.3,components=[{score:combine(absoluteConversion,relativeConversion),weight:.20},{score:combine(absoluteTraffic,relativeTraffic),weight:.20},{score:combine(absoluteProfit,relativeProfit),weight:.25},{score:absoluteLocalization,weight:.15},{score:absolutePrice,weight:.10},{score:absoluteInventory,weight:.10}],known=components.filter(x=>x.score!=null),raw=known.reduce((s,x)=>s+x.score!*x.weight,0)/Math.max(.01,known.reduce((s,x)=>s+x.weight,0)),confidence=p?.confidence??0,variantIncrement=Math.round(raw),adjusted=adjustedScore(raw,confidence),roas=r.adSpend7d>0?r.adRevenue7d/r.adSpend7d:0,investment=Math.round(.35*health+.65*adjusted);return{...r,roas7:roas,relative:variantIncrement,variantIncrement,adjusted,investment,confidence};}).sort((a,b)=>b.investment-a.investment);
    const action=migrated?`先核对 ${migrated.offer} 与承接变体，不把单 SKU 下滑误判为链接下滑`:status==="链接下滑"?"优先检查库存、价格、配送和广告漏斗，只执行一个修复动作":status==="链接增长"?"保持单变量，确认边际 ROAS 达到保本线后再放量":"保持观察，以链接总利润和 TACOS 决定下一动作";
    return{current,previous,change,health,status,action,migrations,variants,components:{demandScore,trafficScore,conversionScore,profitScore,supplyScore,totalSpend,totalAdRevenue}};
  },[linkedRows,profiles]);
  const avgScore=rows.length?Math.round(rows.reduce((s,r)=>s+r.overallScore,0)/rows.length):0;
  const migrationSeries=useMemo(()=>series.flatMap(g=>{const members=rows.filter(r=>g.skus.includes(r.sku)),current=members.reduce((s,r)=>s+r.units7d,0),previous=members.reduce((s,r)=>s+r.previousUnits7d,0),linkChange=previous>0?(current-previous)/previous*100:null,hits=members.filter(r=>{const loss=Math.max(0,r.previousUnits7d-r.units7d),gain=members.filter(x=>x.sku!==r.sku).reduce((s,x)=>s+Math.max(0,x.units7d-x.previousUnits7d),0),decline=r.previousUnits7d>0?(r.units7d-r.previousUnits7d)/r.previousUnits7d*100:null;return decline!=null&&decline<=-20&&linkChange!=null&&linkChange>=-10&&loss>0&&gain/loss>=.6;});return hits.length?[{...g,hits:hits.map(r=>r.offerId||r.sku),linkChange}]:[];}),[series,rows]);
  const symbol=currency==="CNY"?"¥":"₽", money=(v:number|null)=>v==null?"—":`${symbol}${n(v)}`;
  const toggle=(sku:string,checked:boolean)=>setSelected(old=>{const next=new Set(old);checked?next.add(sku):next.delete(sku);return next;});
  const goToCosts=(r:ProductAnalysisRow)=>window.dispatchEvent(new CustomEvent("ozon:navigate",{detail:{page:"products",query:r.offerId||r.sku}}));
  const openAggregate=(title:string)=>setModal({title,subtitle:`${periodText} · ${selected.size?`已关联选择 ${selected.size} 个 SKU`:"当前筛选范围"}`,content:<RawRows rows={[["分析周期",`${periodDays} 个完整自然日`],["等长前期",`${comparison.from} 至 ${comparison.to}`],["SKU 数量",scoped.length],["总销量",total.units],["总销售额",money(total.revenue)],["广告花费",money(total.ad)],["广告销售额",money(total.adRevenue)],["ROAS",total.ad>0?n(total.adRevenue/total.ad):"不可计算"],["期末库存",total.stock]]}/>});
  const openEvidence=(r:ProductAnalysisRow,title:string)=>setModal({title,subtitle:`${r.offerId||r.sku} · ${r.day} · 规则 ${r.ruleVersion}`,content:<><div className="modal-score-summary"><ScoreRing score={r.overallScore} grade={r.grade}/><div><b>{r.diagnosis}</b><span>置信度 {r.confidence}</span><p>{r.action}</p></div></div><RawRows rows={[["分析天数",periodDays],["等长前期",`${comparison.from} 至 ${comparison.to}`],["曝光",r.impressions],["点击",r.clicks],["CTR",n(r.ctr,"%")],["CPC",money(r.cpc)],["广告订单",r.adOrders],["广告销售额",money(r.adRevenue)],["广告花费",money(r.adSpend)],["CVR",n(r.cvr,"%")],["CPA",money(r.cpa)],["CPA 上限",money(r.cpaLimit)],["ROAS",n(r.roas)],["保本 ROAS",n(r.breakEvenRoas)],["周期总销量",r.totalUnits],["周期总销售额",money(r.totalRevenue)],["期末库存",r.stock],["库存覆盖",n(r.inventoryDays," 天")],["周期累计点击",r.clicks3d],["广告归属方式",r.adSource]]}/><div className="formula-box"><h4>计分过程</h4><p>流量 {r.trafficScore}/20 + 转化 {r.conversionScore}/20 + 利润 {r.profitScore}/25 + 库存 {r.inventoryScore}/15 + 放量 {r.scaleScore}/20 = <b>{r.overallScore}/100</b></p><p>CTR、CVR、CPA、ROAS 均由周期原始分子分母重新计算，不对每日比率取平均；分母为 0 时返回“不可计算”。</p></div></>});
  const openLinkEvidence=()=>setModal({title:"链接总盘、变体迁移与双层投资模型",subtitle:`${periodText} · ${linkedRows.length} 个关联 SKU · 规则 product-analysis-v3.0.0`,content:<><RawRows rows={[["本期链接销量",linkDecision.current],["等长前期链接销量",linkDecision.previous],["链接销量变化",linkDecision.change==null?"不可计算":n(linkDecision.change,"%")],["需求趋势分",n(linkDecision.components.demandScore)],["流量获取分",n(linkDecision.components.trafficScore)],["链接转化分",n(linkDecision.components.conversionScore)],["利润健康分",linkDecision.components.profitScore==null?"不可计算":n(linkDecision.components.profitScore)],["供应稳定分",n(linkDecision.components.supplyScore)],["信任与售后", "当前数据源缺失，不计入且不补默认分"],["链接健康分",`${linkDecision.health}/100`],["链接状态",linkDecision.status],["建议动作",linkDecision.action]]}/><div className="formula-box"><h4>变体迁移判定</h4><p>目标变体销量下降 ≥20%，链接合计销量下降不超过 10%，其他变体承接损失销量 ≥60%。当前周期与前一个等长完整周期比较。</p><h4>双层投资分</h4><p>变体增量分由转化、流量、单位利润、集群本地化、价格竞争力和库存准备度组成；单项采用 70% 绝对阈值 + 30% 链接内相对分。最终投资分 = 35% 链接健康分 + 65% 可信度修正后的变体增量分。</p></div></>});
  const openDecisionEvidence=(p:DecisionProfile)=>setModal({title:"30 天状态、事件与边际实验证据",subtitle:`${focus?.offerId||p.sku} · ${periodText} · 规则 product-analysis-v3.0.0`,content:<><RawRows rows={[["生命周期",p.lifecycle],["30 天趋势状态",p.trend],["有效可售/销售日",p.activeDays],["预计销量",p.expectedUnits==null?"不可计算":n(p.expectedUnits)],["实际销量",p.actualUnits],["偏差",p.deltaPercent==null?"不可计算":n(p.deltaPercent,"%")],["连续异常日",p.sustainedDays],["数据可信度",n(p.confidence,"%")],["库存需求匹配度",p.inventoryMatch==null?"不可计算":n(p.inventoryMatch)],["LSI（当前可计算部分）",p.lsi==null?"不可计算":n(p.lsi)],["LSI 数据覆盖",n(p.lsiConfidence,"%")],["边际 CPA",money(p.marginalCpa)],["边际 ROAS",n(p.marginalRoas)],["边际 CVR",p.marginalCvr==null?"不可计算":n(p.marginalCvr*100,"%")],["广告弹性",n(p.adElasticity)],["实验判断",p.experimentDecision],["下一关口",p.nextGate]]}/><div className="formula-box"><h4>事件时间线</h4>{p.events.length?p.events.map(e=><p key={`${e.day}-${e.type}`}>{e.day} · {e.label} · {e.source}</p>):<p>周期内没有检测到可归因事件。</p>}<p><b>归因结论：</b>{p.attribution}</p><h4>自动停止条件</h4>{p.stopConditions.map(x=><p key={x}>• {x}</p>)}<h4>缺失数据与一票否决</h4><p>LSI 缺失：{p.lsiMissing.join("、")||"无"}</p><p>{p.vetoes.length?p.vetoes.join("；"):"未触发一票否决"}</p></div></>});
  const createSeries=async()=>{if(selected.size<2){setMessage("请至少勾选两个需要关联的 SKU");return;}const name=window.prompt("请输入链接/系列名称",`链接-${[...selected].map(s=>rows.find(r=>r.sku===s)?.offerId||s).join("+")}`);if(!name)return;try{await saveProductSeries(null,name,[...selected]);setSeries(await seriesInsights(day));setMessage(`已关联 ${selected.size} 个 SKU：${name}`);}catch(e){setMessage(String(e));}};
  return <>
    <header className="page-header"><div><span className="eyebrow">PRODUCT DECISION SYSTEM</span><h1>产品经营诊断</h1><p>用评分卡与经营看板定位流量、转化、利润、库存和放量风险</p></div></header>
    <section className="card product-analysis-controls"><div className="analysis-mode-switch"><button className={mode==="week"?"active":""} onClick={()=>setMode("week")}>周分析</button><button className={mode==="month"?"active":""} onClick={()=>setMode("month")}>月分析</button><button className={mode==="range"?"active":""} onClick={()=>setMode("range")}>自定义范围</button></div>{mode==="month"?<label><CalendarDays size={17}/>分析月份<input type="month" value={endDay.slice(0,7)} max={previousCompleteDay().slice(0,7)} onChange={e=>{const first=`${e.target.value}-01`,next=addDays(`${e.target.value}-01`,32),last=addDays(`${next.slice(0,7)}-01`,-1);setEndDay(last>previousCompleteDay()?previousCompleteDay():last);}}/></label>:mode==="range"?<div className="range-inputs"><label><CalendarDays size={17}/>开始<input type="date" value={startDay} max={endDay} onChange={e=>setStartDay(e.target.value)}/></label><label>结束<input type="date" value={endDay} min={startDay} max={previousCompleteDay()} onChange={e=>setEndDay(e.target.value)}/></label></div>:<label><CalendarDays size={17}/>本周截止<input type="date" value={endDay} max={previousCompleteDay()} onChange={e=>setEndDay(e.target.value)}/></label>}<label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 SKU、货号或商品名"/></label><span className="badge blue">{periodText} · {periodDays} 天；对比 {comparison.from} 至 {comparison.to}</span></section>
    {message&&<div className="error-banner">{message}</div>}
    <section className="analysis-kpi-grid">
      <button className="card hero-score clickable-card" onClick={()=>openAggregate("整体经营健康度与原始数据")}><ScoreRing score={avgScore} grade="平均分"/><div><span>整体经营健康度</span><strong>{rows.length} 个产品已评价</strong><small>风险产品 {rows.filter(r=>r.overallScore<55).length} 个 · 点击查看</small></div></button>
      <button className="card mini-kpi clickable-card" onClick={()=>openAggregate("链接总销量明细")}><ShoppingCart/><span>链接总销量</span><strong>{total.units}</strong><small>{selected.size?`已选 ${selected.size} 个变体`:"当前筛选结果"}</small></button>
      <button className="card mini-kpi clickable-card" onClick={()=>openAggregate("销售额与广告花费明细")}><WalletCards/><span>链接总销售额</span><strong>{money(total.revenue)}</strong><small>广告费 {money(total.ad)}</small></button>
      <button className="card mini-kpi clickable-card" onClick={()=>openAggregate("广告归属与 ROAS 原始数据")}><Target/><span>广告 ROAS</span><strong>{total.ad>0?n(total.adRevenue/total.ad):"—"}</strong><small>广告销售额 {money(total.adRevenue)}</small></button>
      <button className="card mini-kpi clickable-card" onClick={()=>openAggregate("样本量判断过程")}><CheckCircle2/><span>可判断样本</span><strong>{rows.filter(r=>r.sampleReady).length}/{rows.length}</strong><small>周期 ≥3 天且累计 ≥100 点击</small></button>
    </section>
    {profile&&<section className="decision-engine-grid">
      <button className="card engine-card clickable-card" onClick={()=>openDecisionEvidence(profile)}><Activity/><span>30 天完整状态</span><strong>{profile.lifecycle} · {profile.trend}</strong><small>预计 {profile.expectedUnits==null?"—":n(profile.expectedUnits)} / 实际 {profile.actualUnits} · 可信度 {n(profile.confidence,"%")}</small></button>
      <button className="card engine-card clickable-card" onClick={()=>openDecisionEvidence(profile)}><MapPinned/><span>集群 LSI 与本地化</span><strong>{profile.lsi==null?"不可计算":n(profile.lsi)}</strong><small>库存需求匹配 {profile.inventoryMatch==null?"—":n(profile.inventoryMatch)} · 覆盖 {profile.lsiConfidence}%</small></button>
      <button className="card engine-card clickable-card" onClick={()=>openDecisionEvidence(profile)}><TrendingUp/><span>边际实验决策</span><strong>CPA {money(profile.marginalCpa)} · ROAS {n(profile.marginalRoas)}</strong><small>{profile.experimentDecision}</small></button>
      <button className="card engine-card clickable-card" onClick={()=>openDecisionEvidence(profile)}><ShieldAlert/><span>下一关口 / 自动停止</span><strong>{profile.vetoes.length?`${profile.vetoes.length} 项否决条件`:"可进入下一关口"}</strong><small>{profile.nextGate}</small></button>
    </section>}
    {!!migrationSeries.length&&<section className="card auto-migration-alert"><Link2/><div><h3>自动识别到 {migrationSeries.length} 个疑似变体迁移链接</h3><p>{migrationSeries.map(g=>`${g.name}：${g.hits.join("、")} 下滑，但链接总盘变化 ${n(g.linkChange,"%")}`).join("；")}</p></div><button onClick={()=>{const g=migrationSeries[0];setSelected(new Set(g.skus));const first=rows.find(r=>g.skus.includes(r.sku));if(first)setFocusedSku(first.sku);}}>查看首个链接</button></section>}
    <section className="card product-picker"><div className="section-heading"><div><h2>产品评分卡</h2><p>勾选两个或多个 SKU 建立持久关联；点击卡片仅切换下方诊断看板</p></div><div className="series-actions"><button onClick={createSeries}><Link2 size={15}/>关联选中 SKU</button>{series.map(g=><button key={g.id} className="series-chip" onClick={()=>{setSelected(new Set(g.skus));const first=rows.find(r=>g.skus.includes(r.sku));if(first)setFocusedSku(first.sku);}}>{g.name} · {g.skus.length} SKU</button>)}</div></div><div className="product-card-grid">
      {rows.slice(0,60).map(r=><button type="button" key={r.sku} className={`product-score-card ${focusedSku===r.sku?"active":""}`} onClick={()=>setFocusedSku(r.sku)}>
        <label onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.has(r.sku)} onChange={e=>toggle(r.sku,e.target.checked)}/>链接汇总</label><span className={`grade ${tone(r.overallScore)}`}>{r.grade}</span><strong>{r.offerId||r.sku}</strong><small>{r.name||r.sku}</small><div><b>{r.overallScore}</b><span>分</span><em>置信度 {r.confidence}</em></div>
      </button>)}
      {!busy&&!rows.length&&<div className="empty">所选完整自然日范围没有可分析的经营、广告或库存数据。</div>}
    </div></section>
    {linkedRows.length>1&&<section className="card link-diagnosis-board">
      <button className="link-diagnosis-summary clickable-card" onClick={openLinkEvidence}><div><span>关联链接诊断</span><h2>{linkDecision.status}</h2><p>{linkDecision.action}</p></div><ScoreRing score={linkDecision.health} grade="链接健康"/></button>
      <div className="link-window-kpis"><div><span>本期 {periodDays} 天</span><b>{linkDecision.current} 件</b></div><div><span>等长前期 {periodDays} 天</span><b>{linkDecision.previous} 件</b></div><div><span>链接销量变化</span><b>{linkDecision.change==null?"—":n(linkDecision.change,"%")}</b></div><div><span>关联变体</span><b>{linkedRows.length} SKU</b></div></div>
      <div className="variant-compare"><div className="variant-compare-head"><span>变体</span><span>本期/前期销量</span><span>周期广告费</span><span>周期 ROAS</span><span>增量分 原始/修正</span><span>投资分</span><span>迁移判断</span></div>{linkDecision.variants.map(v=>{const migration=linkDecision.migrations.find(x=>x.sku===v.sku);return <div className="variant-compare-row" key={v.sku}><b>{v.offerId||v.sku}<small>{v.sku}</small></b><span>{v.units7d} / {v.previousUnits7d}</span><span>{money(v.adSpend7d)}</span><span>{n(v.roas7)}</span><span>{v.variantIncrement} / {v.adjusted}<small>可信度 {n(v.confidence,"%")}</small></span><strong>{v.investment}</strong><em className={migration?.isMigration?"migration-hit":""}>{migration?.isMigration?`迁移 · 承接 ${n(migration.carry,"%")}`:"—"}</em></div>})}</div>
    </section>}
    {focus&&<>
      <section className="analysis-detail-grid">
        <button className="card score-board clickable-card" onClick={()=>openEvidence(focus,"五维评分计算过程")}><div className="board-title"><div><span>综合评分</span><h2>{focus.offerId||focus.sku}</h2><small>{focus.sku} · 评分置信度 {focus.confidence}</small></div><ScoreRing score={focus.overallScore} grade={focus.grade}/></div><div className="score-bars"><ScoreBar label="流量质量" score={focus.trafficScore} max={20}/><ScoreBar label="转化效率" score={focus.conversionScore} max={20}/><ScoreBar label="利润安全" score={focus.profitScore} max={25}/><ScoreBar label="库存健康" score={focus.inventoryScore} max={15}/><ScoreBar label="放量条件" score={focus.scaleScore} max={20}/></div></button>
        <button className="card decision-board clickable-card" onClick={()=>openEvidence(focus,"经营评价、证据与建议动作")}><div className="board-icon"><Gauge/></div><span>经营评价</span><h2>{focus.diagnosis}</h2><p>{focus.action}</p><div className={`decision-pill ${focus.sampleReady?"ready":"pending"}`}>{focus.sampleReady?"样本量已达到判断线":periodDays<3?"分析周期至少需要 3 个完整自然日":`还需 ${Math.max(0,100-focus.clicks3d)} 次点击达到判断线`}</div></button>
      </section>
      <section className="analysis-board-grid">
        <button className="card metric-board clickable-card" onClick={()=>openEvidence(focus,"流量与转化漏斗原始数据")}><div className="board-heading"><Target/><div><h3>流量与转化漏斗</h3><p>曝光 → 点击 → 广告订单</p></div></div><div className="funnel"><div><b>{n(focus.impressions)}</b><span>曝光</span></div><i>CTR {n(focus.ctr,"%")}</i><div><b>{n(focus.clicks)}</b><span>点击</span></div><i>CVR {n(focus.cvr,"%")}</i><div><b>{focus.adOrders}</b><span>广告订单</span></div></div><div className="metric-pairs"><span>CPC <b>{money(focus.cpc)}</b></span><span>周期点击 <b>{focus.clicks3d}</b></span></div></button>
        <button className="card metric-board clickable-card" onClick={()=>openEvidence(focus,"利润与广告安全线原始数据")}><div className="board-heading"><WalletCards/><div><h3>利润与广告安全线</h3><p>{focus.adSource}</p></div></div><div className="big-metrics"><div><span>CPA / 上限</span><b>{money(focus.cpa)} / {money(focus.cpaLimit)}</b></div><div><span>ROAS / 保本</span><b>{n(focus.roas)} / {n(focus.breakEvenRoas)}</b></div><div><span>增量 ROAS</span><b>{n(focus.incrementalRoas)}</b></div><div><span>广告费</span><b>{money(focus.adSpend)}</b></div></div>{focus.cpaLimit==null&&<p className="board-alert">成本或历史费率不完整，利润评分已降置信度。</p>}</button>
        <button className="card metric-board clickable-card" onClick={()=>openEvidence(focus,"库存与销售压力原始数据")}><div className="board-heading"><Package/><div><h3>库存与销售压力</h3><p>期末库存 ÷ 所选周期日均销量</p></div></div><div className="inventory-hero"><strong>{focus.stock}</strong><span>期末库存</span><b>{n(focus.inventoryDays," 天")}</b><span>可售天数</span></div><div className="metric-pairs"><span>周期销量 <b>{focus.totalUnits}</b></span><span>周期销售额 <b>{money(focus.totalRevenue)}</b></span><span>期末价格 <b>{money(focus.price)}</b></span></div></button>
      </section>
      {focus.cpaLimit==null&&<section className="card profit-data-gap"><AlertTriangle/><div><h3>利润安全线暂不可计算</h3><p>售价、采购成本、头程和历史平台费率必须同时存在。当前：采购 {money(focus.purchaseCost)}、头程 {money(focus.firstMileCost)}、平台费/件 {money(focus.platformUnitCost)}。</p></div><button onClick={()=>goToCosts(focus)}>前往商品中心补成本</button></section>}
    </>}
    <button className="card scoring-rules clickable-card" onClick={()=>focus&&openEvidence(focus,"评分规则、计分过程与原始证据")}><div className="board-heading"><TrendingUp/><div><h3>评分口径（满分 100）</h3><p>评分用于提示风险，不替代真实利润；点击查看当前产品完整计分过程</p></div></div><div><span><b>流量 20</b>CTR ≥3% 满分</span><span><b>转化 20</b>CVR ≥8% 满分</span><span><b>利润 25</b>CPA 不超过贡献利润</span><span><b>库存 15</b>14–60 天最健康</span><span><b>放量 20</b>增量 ROAS 达保本线</span></div></button>
    <section className="card migration-note"><AlertTriangle/><div><h3>测试纪律</h3><p>每次只修改预算、图片、价格中的一个；至少观察 3 天或累计 100 点击。放量时看增量 ROAS，低于保本 ROAS 立即回退；周复盘优先看链接总利润与 TACOS。</p></div></section>
    {modal&&<div className="analysis-modal-backdrop" onMouseDown={()=>setModal(null)}><section className="analysis-modal" onMouseDown={e=>e.stopPropagation()}><header><div><Database/><div><h2>{modal.title}</h2><p>{modal.subtitle}</p></div></div><button onClick={()=>setModal(null)} aria-label="关闭"><X/></button></header><div className="analysis-modal-body">{modal.content}</div></section></div>}
  </>;
}
