import {useEffect,useMemo,useState} from "react";
import {invoke} from "@tauri-apps/api/core";
import {FileDown,FilePlus2,Plus,Printer,Save,Trash2} from "lucide-react";
import "./purchase-orders.css";

type Item={productName:string;sku:string;imageUrl:string;unitPrice:string;packageLengthCm:string;packageWidthCm:string;packageHeightCm:string;unitWeightKg:string;unitsPerCarton:string;cartonWeightKg:string;cartonLengthCm:string;cartonWidthCm:string;cartonHeightCm:string;cartonCount:string;quantity:string;unit:string;note:string};
type Form={orderNo:string;title:string;operator:string;orderDate:string;expectedShipAt:string;factoryAddress:string;approver:string;note:string;items:Item[]};
type Row={id:number;orderNo:string;title:string;operator:string;orderDate:string;status:string;itemCount:number;updatedAt:string};
const day=()=>new Date().toISOString().slice(0,10),emptyItem=():Item=>({productName:"",sku:"",imageUrl:"",unitPrice:"",packageLengthCm:"",packageWidthCm:"",packageHeightCm:"",unitWeightKg:"",unitsPerCarton:"",cartonWeightKg:"",cartonLengthCm:"",cartonWidthCm:"",cartonHeightCm:"",cartonCount:"",quantity:"",unit:"个",note:""});
const blank=():Form=>({orderNo:`CG-${day().replaceAll("-","")}-001`,title:"采购清单",operator:"",orderDate:day(),expectedShipAt:"",factoryAddress:"",approver:"",note:"",items:[emptyItem()]});
const n=(s:string)=>{const x=Number(s);return Number.isFinite(x)?x:0},money=(v:number)=>`¥${v.toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export function PurchaseOrderPage(){
 const[form,setForm]=useState<Form>(blank),[id,setId]=useState<number|null>(null),[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState("");
 const totals=useMemo(()=>form.items.reduce((a,x)=>{const amount=n(x.unitPrice)*n(x.quantity),volume=n(x.cartonLengthCm)*n(x.cartonWidthCm)*n(x.cartonHeightCm)/1e6*n(x.cartonCount);return{cartons:a.cartons+n(x.cartonCount),quantity:a.quantity+n(x.quantity),amount:a.amount+amount,weight:a.weight+n(x.cartonWeightKg)*n(x.cartonCount),volume:a.volume+volume}}, {cartons:0,quantity:0,amount:0,weight:0,volume:0}),[form.items]);
 const load=async()=>{const x=await invoke<{orders:Row[]}>("purchase_order_command",{command:"list",id:null,payload:null});setRows(x.orders)};useEffect(()=>{void load().catch(e=>setMessage(String(e)))},[]);
 const set=(key:keyof Form,value:any)=>setForm(x=>({...x,[key]:value}));const item=(i:number,key:keyof Item,value:string)=>setForm(x=>({...x,items:x.items.map((r,j)=>j===i?{...r,[key]:value}:r)}));
 const save=async()=>{try{const x=await invoke<{id:number}>("purchase_order_command",{command:"save",id,payload:form});setId(x.id);setMessage("采购单草稿已保存");await load()}catch(e){setMessage(String(e))}};
 const open=async(row:Row)=>{try{setForm(await invoke<Form>("purchase_order_command",{command:"detail",id:row.id,payload:null}));setId(row.id);setMessage("")}catch(e){setMessage(String(e))}};
 const archive=async()=>{if(id==null||!confirm("确认删除当前采购单？"))return;try{await invoke("purchase_order_command",{command:"archive",id,payload:null});setId(null);setForm(blank());await load()}catch(e){setMessage(String(e))}};
 const exportExcel=async()=>{try{const x=await invoke<{path:string}>("purchase_order_command",{command:"export_excel",id:null,payload:form});setMessage(`Excel 已导出：${x.path}`)}catch(e){setMessage(String(e))}};
 return <div className="po-page"><header className="po-hero"><div><span>PURCHASE ORDER CENTER</span><h1>采购单添加</h1><p>按产品维护采购、包装、装箱与出货信息，自动计算数量、金额、重量和体积。</p></div><div><button onClick={()=>{setId(null);setForm(blank());setMessage("")}}><FilePlus2/>新建</button><button className="primary" onClick={()=>void save()}><Save/>保存草稿</button><button onClick={()=>void exportExcel()}><FileDown/>导出 Excel</button><button onClick={()=>window.print()}><Printer/>打印 / PDF</button>{id&&<button className="danger" onClick={()=>void archive()}><Trash2/>删除</button>}</div></header>
 <div className="po-layout"><aside className="po-history"><h2>采购单记录</h2><p>{rows.length} 份有效草稿</p>{rows.map(x=><button className={id===x.id?"active":""} key={x.id} onClick={()=>void open(x)}><b>{x.orderNo}</b><span>{x.title||"采购清单"} · {x.orderDate}</span><small>{x.itemCount} 项 · {x.operator||"未填经办人"}</small></button>)}{!rows.length&&<div className="po-empty">保存后会显示在这里</div>}</aside>
 <main className="po-sheet"><section className="po-meta"><div className="po-title"><input value={form.title} onChange={e=>set("title",e.target.value)}/><b>- 采购清单</b></div><div className="po-meta-grid"><label>采购单编号<input value={form.orderNo} onChange={e=>set("orderNo",e.target.value)}/></label><label>采购日期<input type="date" value={form.orderDate} onChange={e=>set("orderDate",e.target.value)}/></label><label>经办人<input value={form.operator} onChange={e=>set("operator",e.target.value)}/></label><label>预计出货时间<input type="date" value={form.expectedShipAt} onChange={e=>set("expectedShipAt",e.target.value)}/></label><label>工厂地址<input value={form.factoryAddress} onChange={e=>set("factoryAddress",e.target.value)}/></label><label>领导审批<input value={form.approver} onChange={e=>set("approver",e.target.value)}/></label></div></section>
 <div className="po-toolbar"><h2>产品明细</h2><button onClick={()=>set("items",[...form.items,emptyItem()])}><Plus/>添加产品</button></div><div className="po-table-wrap"><table><thead><tr><th>中文品名</th><th>SKU</th><th>图片 URL</th><th className="yellow">单价</th><th>包装规格 cm<br/>长 / 宽 / 高</th><th>重量 kg</th><th>装箱率</th><th>外箱重量 kg</th><th>外箱规格 cm<br/>长 / 宽 / 高</th><th className="blue">箱数</th><th className="yellow">数量</th><th>单位</th><th className="yellow">总价</th><th>总体积 m³</th><th>备注</th><th/></tr></thead><tbody>{form.items.map((x,i)=>{const amount=n(x.unitPrice)*n(x.quantity),volume=n(x.cartonLengthCm)*n(x.cartonWidthCm)*n(x.cartonHeightCm)/1e6*n(x.cartonCount);return <tr key={i}><td><input value={x.productName} onChange={e=>item(i,"productName",e.target.value)}/></td><td><input value={x.sku} onChange={e=>item(i,"sku",e.target.value)}/></td><td><input value={x.imageUrl} onChange={e=>item(i,"imageUrl",e.target.value)} placeholder="https://"/></td><td className="yellow"><input value={x.unitPrice} onChange={e=>item(i,"unitPrice",e.target.value)}/></td><td><div className="triple">{(["packageLengthCm","packageWidthCm","packageHeightCm"] as const).map(k=><input key={k} value={x[k]} onChange={e=>item(i,k,e.target.value)}/>)}</div></td><td><input value={x.unitWeightKg} onChange={e=>item(i,"unitWeightKg",e.target.value)}/></td><td><input value={x.unitsPerCarton} onChange={e=>item(i,"unitsPerCarton",e.target.value)}/></td><td><input value={x.cartonWeightKg} onChange={e=>item(i,"cartonWeightKg",e.target.value)}/></td><td><div className="triple">{(["cartonLengthCm","cartonWidthCm","cartonHeightCm"] as const).map(k=><input key={k} value={x[k]} onChange={e=>item(i,k,e.target.value)}/>)}</div></td><td className="blue"><input value={x.cartonCount} onChange={e=>item(i,"cartonCount",e.target.value)}/></td><td className="yellow"><input value={x.quantity} onChange={e=>item(i,"quantity",e.target.value)}/></td><td><input value={x.unit} onChange={e=>item(i,"unit",e.target.value)}/></td><td className="yellow"><b>{money(amount)}</b></td><td>{volume?volume.toFixed(3):"—"}</td><td><input value={x.note} onChange={e=>item(i,"note",e.target.value)}/></td><td><button disabled={form.items.length===1} onClick={()=>set("items",form.items.filter((_,j)=>j!==i))}><Trash2/></button></td></tr>})}</tbody><tfoot><tr><td>合计</td><td colSpan={8}></td><td>{totals.cartons||"—"}</td><td>{totals.quantity||"—"}</td><td>个</td><td>{money(totals.amount)}</td><td>{totals.volume.toFixed(3)}</td><td>{totals.weight.toFixed(2)} kg</td><td></td></tr></tfoot></table></div><label className="po-note">采购单备注<textarea value={form.note} onChange={e=>set("note",e.target.value)}/></label></main></div>{message&&<div className="po-message">{message}</div>}</div>
}
