import { useEffect, useState } from "react";
import { Archive, ExternalLink, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { deleteSelectionCategory, deleteSelectionItem, openListingSupplierUrl, saveSelectionCategory, saveSelectionItem, selectionCategories, selectionItems } from "./bridge";
import type { SelectionCategory, SelectionItem, SelectionItemInput } from "./types";
import "./selection-library.css";

const emptyItem:SelectionItemInput={id:null,categoryId:null,productName:"",imageUrl:"",targetMarket:"俄罗斯 Ozon",competitorUrl:"",purchaseUrl:"",competitorPrice:null,purchasePrice:null,targetPrice:null,estimatedMonthlySales:null,weightKg:null,lengthCm:null,widthCm:null,heightCm:null,status:"待调研",priority:"中",tags:"",advantages:"",risks:"",notes:""};
const numberValue=(value:string)=>value===""?null:Number(value);

export function SelectionLibraryPage({shopId}:{shopId:string}){
  const [categories,setCategories]=useState<SelectionCategory[]>([]),[items,setItems]=useState<SelectionItem[]>([]),[query,setQuery]=useState(""),[categoryId,setCategoryId]=useState<number|null>(null),[status,setStatus]=useState(""),[form,setForm]=useState<SelectionItemInput|null>(null),[categoryForm,setCategoryForm]=useState<{id:number|null;name:string;note:string}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=async()=>{const [nextCategories,nextItems]=await Promise.all([selectionCategories(),selectionItems(query,categoryId,status)]);setCategories(nextCategories);setItems(nextItems)};
  useEffect(()=>{void load().catch(error=>setMessage(String(error)))},[shopId,query,categoryId,status]);
  const saveItem=async()=>{if(!form)return;setBusy(true);try{await saveSelectionItem(form);setForm(null);setMessage("选品资料已保存。");await load()}catch(error){setMessage(String(error))}finally{setBusy(false)}};
  const edit=(item:SelectionItem)=>setForm({id:item.id,categoryId:item.categoryId,productName:item.productName,imageUrl:item.imageUrl,targetMarket:item.targetMarket,competitorUrl:item.competitorUrl,purchaseUrl:item.purchaseUrl,competitorPrice:item.competitorPrice,purchasePrice:item.purchasePrice,targetPrice:item.targetPrice,estimatedMonthlySales:item.estimatedMonthlySales,weightKg:item.weightKg,lengthCm:item.lengthCm,widthCm:item.widthCm,heightCm:item.heightCm,status:item.status,priority:item.priority,tags:item.tags,advantages:item.advantages,risks:item.risks,notes:item.notes});
  return <div className="selection-library">
    <header className="page-header compact"><div><span className="eyebrow">PRODUCT RESEARCH LIBRARY</span><h1>选品资料库</h1><p>按类目沉淀候选产品、竞品、采购来源、成本和选品判断</p></div><button className="dark-button" onClick={()=>setForm({...emptyItem})}><Plus size={16}/>新增选品</button></header>
    {message&&<div className="selection-message">{message}</div>}
    <section className="selection-toolbar card"><label className="selection-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索产品、标签、市场或备注"/></label><select value={categoryId??""} onChange={e=>setCategoryId(e.target.value?Number(e.target.value):null)}><option value="">全部类目</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}（{x.itemCount}）</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{["待调研","调研中","待打样","已通过","已放弃"].map(x=><option key={x}>{x}</option>)}</select><button className="outline-button" onClick={()=>setCategoryForm({id:null,name:"",note:""})}><Plus size={15}/>管理类目</button></section>
    <section className="selection-summary"><div><span>候选产品</span><strong>{items.length}</strong></div><div><span>已通过</span><strong>{items.filter(x=>x.status==="已通过").length}</strong></div><div><span>待打样</span><strong>{items.filter(x=>x.status==="待打样").length}</strong></div><div><span>高优先级</span><strong>{items.filter(x=>x.priority==="高").length}</strong></div></section>
    <section className="selection-grid">{items.map(item=><article className="selection-card" key={item.id}>
      <div className="selection-image">{item.imageUrl?<img src={item.imageUrl} alt=""/>:<Archive size={30}/>}<span className={`priority ${item.priority}`}>{item.priority}优先级</span></div>
      <div className="selection-card-body"><div className="selection-card-title"><div><small>{item.categoryName||"未分类"} · {item.targetMarket||"未设置市场"}</small><h3>{item.productName}</h3></div><span>{item.status}</span></div>
      <div className="selection-metrics"><span>竞品价<b>{item.competitorPrice??"—"}</b></span><span>采购价<b>{item.purchasePrice??"—"}</b></span><span>目标售价<b>{item.targetPrice??"—"}</b></span><span>预计月销<b>{item.estimatedMonthlySales??"—"}</b></span></div>
      {(item.lengthCm||item.widthCm||item.heightCm||item.weightKg)&&<p className="selection-spec">包装 {item.lengthCm??"—"} × {item.widthCm??"—"} × {item.heightCm??"—"} cm · {item.weightKg??"—"} kg</p>}
      {item.tags&&<p className="selection-tags">{item.tags.split(/[,，]/).filter(Boolean).map(tag=><i key={tag}>{tag.trim()}</i>)}</p>}
      {item.notes&&<p className="selection-notes">{item.notes}</p>}
      <div className="selection-links"><button disabled={!item.competitorUrl} onClick={()=>openListingSupplierUrl(item.competitorUrl)}><ExternalLink size={14}/>竞品链接</button><button disabled={!item.purchaseUrl} onClick={()=>openListingSupplierUrl(item.purchaseUrl)}><ExternalLink size={14}/>采购链接</button></div>
      <div className="selection-card-actions"><button className="outline-button" onClick={()=>edit(item)}><Pencil size={14}/>编辑</button><button className="icon-button danger" title="删除" onClick={async()=>{if(!confirm(`确认删除“${item.productName}”吗？`))return;await deleteSelectionItem(item.id);await load()}}><Trash2 size={15}/></button></div></div>
    </article>)}{!items.length&&<div className="empty-note selection-empty">暂无选品资料，点击“新增选品”开始建立资料库。</div>}</section>
    {form&&<div className="modal-backdrop selection-modal-backdrop"><div className="modal-card selection-modal"><div className="modal-title"><div><span className="eyebrow">PRODUCT CANDIDATE</span><h2>{form.id?"编辑选品资料":"新增选品资料"}</h2><p>完整记录候选产品的来源、成本、尺寸与调研判断</p></div><button className="selection-modal-close" onClick={()=>setForm(null)} aria-label="关闭"><X size={20}/></button></div><div className="selection-form">
      <section className="selection-form-section"><header><span>01</span><div><h3>基础信息</h3><p>确认候选产品归属和目标市场</p></div></header><div className="selection-fields basic"><label className="product-name">产品名称 <em>*</em><input value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} placeholder="请输入候选产品名称" autoFocus/></label><label>类目<select value={form.categoryId??""} onChange={e=>setForm({...form,categoryId:e.target.value?Number(e.target.value):null})}><option value="">未分类</option>{categories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>目标市场<input value={form.targetMarket} onChange={e=>setForm({...form,targetMarket:e.target.value})} placeholder="例如：俄罗斯 Ozon"/></label><label className="image-link">产品图片链接<input value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label></div></section>
      <section className="selection-form-section"><header><span>02</span><div><h3>链接与价格</h3><p>保存竞品页面、采购来源和价格测算数据</p></div></header><div className="selection-fields links"><label>竞品链接<input value={form.competitorUrl} onChange={e=>setForm({...form,competitorUrl:e.target.value})} placeholder="Ozon / Amazon 商品链接"/></label><label>采购链接<input value={form.purchaseUrl} onChange={e=>setForm({...form,purchaseUrl:e.target.value})} placeholder="1688 / 工厂商品链接"/></label>{[['竞品价格','competitorPrice'],['采购价格','purchasePrice'],['目标售价','targetPrice'],['预计月销量','estimatedMonthlySales']].map(([label,key])=><label key={key}>{label}<input type="number" min="0" step={key==='estimatedMonthlySales'?'1':'0.01'} value={(form as any)[key]??""} onChange={e=>setForm({...form,[key]:numberValue(e.target.value)})} placeholder="0"/></label>)}</div></section>
      <section className="selection-form-section compact"><header><span>03</span><div><h3>包装参数</h3><p>用于预估物流成本和体积重</p></div></header><div className="selection-fields package">{[['重量','weightKg','kg'],['长度','lengthCm','cm'],['宽度','widthCm','cm'],['高度','heightCm','cm']].map(([label,key,unit])=><label key={key}>{label}<div className="unit-input"><input type="number" min="0" step="0.01" value={(form as any)[key]??""} onChange={e=>setForm({...form,[key]:numberValue(e.target.value)})} placeholder="0"/><span>{unit}</span></div></label>)}</div></section>
      <section className="selection-form-section"><header><span>04</span><div><h3>选品判断</h3><p>记录进度、机会点和潜在风险</p></div></header><div className="selection-fields decision"><label>状态<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["待调研","调研中","待打样","已通过","已放弃"].map(x=><option key={x}>{x}</option>)}</select></label><label>优先级<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{["高","中","低"].map(x=><option key={x}>{x}</option>)}</select></label><label className="tags-field">标签<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="多个标签使用逗号分隔，如：轻小件，低竞争"/></label><label>产品优势<textarea value={form.advantages} onChange={e=>setForm({...form,advantages:e.target.value})} placeholder="市场机会、差异化卖点、利润空间…"/></label><label>风险与难点<textarea value={form.risks} onChange={e=>setForm({...form,risks:e.target.value})} placeholder="认证、侵权、季节性、供应稳定性…"/></label><label className="notes-field">调研备注<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="补充记录调研结论和下一步动作"/></label></div></section>
    </div><div className="selection-modal-footer"><span>{form.productName.trim()?`正在编辑：${form.productName}`:"请先填写产品名称"}</span><div><button className="outline-button" onClick={()=>setForm(null)}>取消</button><button className="dark-button" disabled={busy||!form.productName.trim()} onClick={saveItem}>{busy?"保存中…":"保存选品资料"}</button></div></div></div></div>}
    {categoryForm&&<div className="modal-backdrop"><div className="modal-card category-modal"><div className="modal-title"><h2>类目管理</h2><button className="icon-button" onClick={()=>setCategoryForm(null)}><X/></button></div><div className="category-list">{categories.map(cat=><div key={cat.id}><span><b>{cat.name}</b><small>{cat.itemCount} 个产品 · {cat.note||"无备注"}</small></span><button className="icon-button" onClick={()=>setCategoryForm({id:cat.id,name:cat.name,note:cat.note})}><Pencil size={14}/></button><button className="icon-button danger" onClick={async()=>{if(!confirm(`删除类目“${cat.name}”？其中产品会保留为未分类。`))return;await deleteSelectionCategory(cat.id);await load()}}><Trash2 size={14}/></button></div>)}</div><div className="category-editor"><label>类目名称<input value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})}/></label><label>备注<input value={categoryForm.note} onChange={e=>setCategoryForm({...categoryForm,note:e.target.value})}/></label></div><div className="modal-actions"><button className="outline-button" onClick={()=>setCategoryForm({id:null,name:"",note:""})}>清空</button><button className="dark-button" disabled={!categoryForm.name.trim()} onClick={async()=>{await saveSelectionCategory(categoryForm);setCategoryForm({id:null,name:"",note:""});await load()}}>保存类目</button></div></div></div>}
  </div>
}
