import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, KeyRound, Plus, RefreshCw, RotateCw, ShieldCheck, Store, XCircle } from "lucide-react";
import { wbShopCenter } from "./bridge";
import "./wb-shop-api-center.css";

type ShopRow={id:string;name:string;sellerType:string;legalEntityName?:string|null;currency:string;timezone?:string|null;country?:string|null;status:string;createdAt:string;updatedAt:string};
type Credential={id:string;shopId:string;maskedHint:string;status:string;lastValidatedAt?:string|null;lastValidationStatus?:string|null;createdAt:string};
type Capability={shopId:string;capability:string;status:string;lastCheckedAt?:string|null;errorCode?:string|null;errorMessage?:string|null};
type Health={shopId:string;capability:string;status:string;lastSuccessfulRequestAt?:string|null;lastFailureAt?:string|null;lastErrorCode?:string|null;lastErrorMessage?:string|null;latencyMs?:number|null;rateLimitState?:string|null};
type Run={id:string;shopId:string;resourceType:string;status:string;startedAt?:string|null;finishedAt?:string|null;recordsProcessed:number;recordsSucceeded:number;recordsFailed:number;errorCode?:string|null;errorMessage?:string|null;retryCount:number};
type Audit={id:number;shopId?:string|null;actor:string;action:string;metadata:unknown;createdAt:string};
type Center={shops:ShopRow[];credentials:Credential[];capabilities:Capability[];health:Health[];runs:Run[];audits:Audit[];resources:string[];capabilityNames:string[]};
const empty:Center={shops:[],credentials:[],capabilities:[],health:[],runs:[],audits:[],resources:[],capabilityNames:[]};
const labels:Record<string,string>={content:"Content",prices:"Prices",marketplace:"Marketplace",fbw:"FBW",promotion:"Promotion",finance:"Finance",analytics:"Analytics",documents:"Documents",products:"商品",orders:"订单",inventory:"库存",fbw_supplies:"FBW 供货",advertising:"广告"};
const healthIcon=(status:string)=>status==="healthy"?<CheckCircle2/>:status==="rate_limited"||status==="degraded"?<AlertTriangle/>:status==="unauthorized"||status==="error"?<XCircle/>:<Clock3/>;
const time=(v?:string|null)=>v?new Date(v).toLocaleString("zh-CN") : "—";

export function WbShopApiCenter(){
 const [data,setData]=useState<Center>(empty),[selected,setSelected]=useState(""),[tab,setTab]=useState<"overview"|"api"|"sync"|"audit">("overview"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[showAdd,setShowAdd]=useState(false),[form,setForm]=useState({name:"",sellerType:"local",legalEntityName:"",currency:"RUB",timezone:"Europe/Moscow",country:"RU",token:""});
 const load=async()=>{setBusy(true);setError("");try{const next=await wbShopCenter<Center>("dashboard");setData(next);setSelected(old=>next.shops.some(s=>s.id===old)?old:(next.shops[0]?.id||""));}catch(e){setError(String(e))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const shop=data.shops.find(s=>s.id===selected),credential=data.credentials.find(c=>c.shopId===selected&&c.status==="active"),caps=data.capabilities.filter(c=>c.shopId===selected),health=data.health.filter(h=>h.shopId===selected),runs=data.runs.filter(r=>r.shopId===selected),audits=data.audits.filter(a=>a.shopId===selected);
 const healthy=health.filter(h=>h.status==="healthy").length, fresh=useMemo(()=>new Set(runs.filter(r=>r.status==="success").map(r=>r.resourceType)).size,[runs]);
 const act=async(action:string,payload:Record<string,unknown>={})=>{setBusy(true);setError("");try{const next=await wbShopCenter<Center>(action,payload);if(next?.shops)setData(next);else await load()}catch(e){setError(String(e))}finally{setBusy(false)}};
 const create=async()=>{if(!form.name.trim())return setError("请输入店铺名称");setBusy(true);setError("");try{const result=await wbShopCenter<{shopId:string}>("create_shop",form);setShowAdd(false);setForm({...form,name:"",legalEntityName:"",token:""});await load();setSelected(result.shopId)}catch(e){setError(String(e))}finally{setBusy(false)}};
 const rotate=async()=>{const token=window.prompt("输入新的 Wildberries Token。旧 Token 将保留为 disabled：");if(token)await act("rotate_token",{shopId:selected,token})};
 return <section className="wb-center">
  <header className="wb-center-head"><div><span>WILDBERRIES ERP · CONNECTION FOUNDATION</span><h1>店铺与 API 中心</h1><p>统一管理店铺身份、加密凭据、API 能力、数据新鲜度与同步恢复。</p></div><div><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?"spin":""} size={16}/>刷新</button><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={16}/>添加店铺</button></div></header>
  {error&&<div className="wb-center-error"><AlertTriangle size={17}/>{error}</div>}
  {!data.shops.length&&!busy?<div className="wb-center-empty"><Store/><h2>尚未连接 Wildberries 店铺</h2><p>添加第一个店铺，Token 将通过 Windows DPAPI 加密保存。</p><button className="primary" onClick={()=>setShowAdd(true)}>添加店铺</button></div>:<>
   <div className="wb-shop-strip">{data.shops.map(s=><button key={s.id} className={selected===s.id?"active":""} onClick={()=>setSelected(s.id)}><Store/><span><b>{s.name}</b><small>{s.currency} · {s.sellerType}</small></span><i className={s.status}>{s.status}</i></button>)}</div>
   {shop&&<><div className="wb-summary"><article><ShieldCheck/><span>API Health<b>{healthy} / 8 Healthy</b></span></article><article><Clock3/><span>Data Freshness<b>{fresh} / 7 Fresh</b></span></article><article><AlertTriangle/><span>Sync Errors<b>{runs.reduce((n,r)=>n+r.recordsFailed,0)}</b></span></article><article><RefreshCw/><span>Last Successful Sync<b>{time(runs.find(r=>r.status==="success")?.finishedAt)}</b></span></article></div>
   <nav className="wb-center-tabs">{(["overview","api","sync","audit"] as const).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{({overview:"概览",api:"API 连接",sync:"同步任务",audit:"审计日志"})[x]}</button>)}</nav>
   {tab==="overview"&&<div className="wb-center-grid"><article className="wb-panel"><h2>{shop.name}</h2><dl><dt>平台</dt><dd>Wildberries</dd><dt>状态</dt><dd>{shop.status}</dd><dt>主体</dt><dd>{shop.legalEntityName||"—"}</dd><dt>币种 / 时区</dt><dd>{shop.currency} · {shop.timezone||"—"}</dd><dt>国家</dt><dd>{shop.country||"—"}</dd></dl></article><article className="wb-panel"><h2>能力概览</h2><div className="cap-grid">{data.capabilityNames.map(name=>{const h=health.find(x=>x.capability===name);return <div className={`cap ${h?.status||"unknown"}`} key={name}>{healthIcon(h?.status||"unknown")}<span><b>{labels[name]||name}</b><small>{h?.status||"unknown"}{h?.latencyMs!=null?` · ${h.latencyMs} ms`:""}</small></span></div>})}</div></article></div>}
   {tab==="api"&&<div className="wb-panel"><div className="panel-title"><div><h2>API 凭据与能力</h2><p>完整 Token 永不返回前端或写入审计日志。</p></div><div><button onClick={rotate}><RotateCw size={15}/>轮换 Token</button><button className="primary" disabled={!credential||busy} onClick={()=>void act("validate",{shopId:selected})}><ShieldCheck size={15}/>验证并检测能力</button></div></div><div className="credential"><KeyRound/><span><b>{credential?.maskedHint||"未配置 Token"}</b><small>{credential?`${credential.status} · 上次验证 ${time(credential.lastValidatedAt)}`:"请轮换或添加 Token"}</small></span></div><table><thead><tr><th>业务域</th><th>能力</th><th>健康度</th><th>最后检测</th><th>说明</th></tr></thead><tbody>{data.capabilityNames.map(name=>{const c=caps.find(x=>x.capability===name),h=health.find(x=>x.capability===name);return <tr key={name}><td>{labels[name]||name}</td><td>{c?.status||"unknown"}</td><td><span className={`status ${h?.status||"unknown"}`}>{h?.status||"unknown"}</span></td><td>{time(c?.lastCheckedAt)}</td><td>{c?.errorMessage||"—"}</td></tr>})}</tbody></table></div>}
   {tab==="sync"&&<div className="wb-panel"><div className="panel-title"><div><h2>同步任务中心</h2><p>重复点击会由店铺 + 资源活动锁去重。</p></div><button className="primary" onClick={()=>void act("sync",{shopId:selected,resourceType:"all"})}>Initial / Sync All</button></div><div className="sync-actions">{data.resources.map(r=><button key={r} onClick={()=>void act("sync",{shopId:selected,resourceType:r})}>同步{labels[r]||r}</button>)}</div><table><thead><tr><th>资源</th><th>状态</th><th>开始</th><th>完成</th><th>进度</th><th>错误</th><th>操作</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{labels[r.resourceType]||r.resourceType}</td><td><span className={`status ${r.status}`}>{r.status}</span></td><td>{time(r.startedAt)}</td><td>{time(r.finishedAt)}</td><td>{r.recordsSucceeded}/{r.recordsProcessed}</td><td>{r.errorMessage||"—"}</td><td>{r.status==="pending"?<button onClick={()=>void act("cancel",{runId:r.id})}>取消</button>:["failed","partial","cancelled"].includes(r.status)?<button onClick={()=>void act("retry",{runId:r.id})}>重试</button>:"—"}</td></tr>)}{!runs.length&&<tr><td colSpan={7}>暂无同步记录</td></tr>}</tbody></table></div>}
   {tab==="audit"&&<div className="wb-panel"><h2>审计日志</h2><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>元数据</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{time(a.createdAt)}</td><td>{a.actor}</td><td>{a.action}</td><td><code>{JSON.stringify(a.metadata)}</code></td></tr>)}</tbody></table></div>}</>}
  </>}
  {showAdd&&<div className="wb-modal"><form onSubmit={e=>{e.preventDefault();void create()}}><h2>添加 Wildberries 店铺</h2><label>店铺名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two"><label>卖家类型<select value={form.sellerType} onChange={e=>setForm({...form,sellerType:e.target.value})}><option value="local">本土</option><option value="cross_border">跨境</option><option value="unknown">未知</option></select></label><label>币种<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label></div><label>公司主体<input value={form.legalEntityName} onChange={e=>setForm({...form,legalEntityName:e.target.value})}/></label><div className="two"><label>时区<input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label><label>国家<input value={form.country} onChange={e=>setForm({...form,country:e.target.value.toUpperCase()})}/></label></div><label>API Token<input type="password" autoComplete="new-password" value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/></label><p>保存后 Token 将被加密；能力检测需要您点击“验证并检测能力”。</p><div><button type="button" onClick={()=>setShowAdd(false)}>取消</button><button className="primary" disabled={busy}>创建店铺</button></div></form></div>}
 </section>
}
